### ISSUE TITLE
Cache Firewall

### ISSUE THREAD

**Issue by HookWoods** [2LStudios-MC/FlameCord#1]
Hello, I was just thinking in your FirewallManager why you weren't using a Cache (from guava or Caffeine) instead? It would be better (not in performance cause it will be the same) but in terms of code cause, you could remove your tick system with your thread at first, and also I think of an idea. 
For example, your firewall is cleared every 2 minutes. If an IP is blacklisted at 1m58 of this thread, it will be only blacklisted for 2 seconds and can make a new attack very fast. Instead with a cache, you can set custom eviction time for the key (and like that, each IP will be blacklisted example 2 minute and will be auto evicted by the cache and not a global thread that evicts all IP at the same time)

I can make a PR if you want (I'm also working on a custom fork of WaterFall to patch some CPU problem and packet crasher or other bugs like that)

**Comment by LinsaFTW** [comment]
The firewall system is not really a fix but just a simple system to avoid getting too many ips repeatedly getting checked. I could make that but idk if it's really a gain to store a timestamp for each blocked ip.

**Comment by LinsaFTW** [comment]
Closed. If someday i come to improve the firewall system and make it consistent, i will add support for this.
