### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by reussy** [2LStudios-MC/FlameCord#10]
I have this error in console:

https://paste.md-5.net/lezariluru.cs

I have PremiumConnector plugin
https://www.spigotmc.org/resources/premiumconnector-bungeecord.20957/

**Comment by Etrayed** [comment]
This is an error caused by the PremiumConnector plugin. You should probably create an issue on their github repo (https://github.com/Corenb/PremiumConnector). But on the first look the plugins tries to redirect you to a server that does not exist.
