### ISSUE TITLE
Kicked whilst connecting to lobby: You are already connected to this proxy!

### ISSUE THREAD

**Issue by Dungjava** [2lstudios-mc/FlameCord#104]
Hello i using FlameCord 0.8.1
So i joined server and say need join 1 more so i joined and i can't join server 
![image](https://user-images.githubusercontent.com/99890979/160393929-3d6412ef-96d1-4556-b944-47b25aff1050.png)

**Comment by linsaftw** [comment]
Cannot reproduce. Try with Waterfall and see if the same issues happens. If so, report to Waterfall.
