### ISSUE TITLE
processor issue 

### ISSUE THREAD

**Issue by makemp1997** [2lstudios-mc/FlameCord#105]
Hello,

I have an issue that when FlameCord runs after a few minutes that my server starting at 100% (see screenshots :
![Screenshot_6](https://user-images.githubusercontent.com/22965328/160530824-c19d171b-6075-4cb6-aca2-e7bc3d64dd4a.png)  
![Screenshot_1](https://user-images.githubusercontent.com/22965328/160530879-b0173ad1-60ba-40a2-a7a4-104000ecbfed.png) ), sadly it also effecting the whole server. The weekend before last weekend I only updated the java to java 17 so around last week the lagging stat noticing. So after try and error I decided to reinstall the entire server sadly however it seems that didn't solve it. Anyway in most every case that FlameCord was somehow in the top so I am wondering what cause this so I am wondering can you say what might cause this or is it something with the combination of Java 17?

Greetings,
makemp1997

**Comment by linsaftw** [comment]
Try java 8 and see if the same issue happens, if so, then it might be an issue with Netty. Reopen if you keep having issues.
