### ISSUE TITLE
i cant find release tab 

### ISSUE THREAD

**Issue by gokul6350** [2lstudios-mc/FlameCord#107]

**Comment by INotSleep** [comment]
No files in realise tab*

**Comment by linsaftw** [comment]
You can get FlameCord on MC-Market.

**Comment by gokul6350** [comment]
![image](https://user-images.githubusercontent.com/64578167/161197716-8d5599f1-0043-4f98-a42c-5b66b8360c02.png)
its paid

**Comment by gokul6350** [comment]
![image](https://user-images.githubusercontent.com/64578167/161197815-8b15d33d-b0a3-40e5-acde-e9c22375eb39.png)

**Comment by linsaftw** [comment]
You can compile if you want it free. We removed releases because we are having economic issues.

**Comment by gokul6350** [comment]
Ok i can understand circumstances  for a developers 
but i m not good in java so how to compile

**Comment by linsaftw** [comment]
> Ok i can understand circumstances for a developers but i m not good in java so how to compile

There is a simple guide explained in the readme of the repository.
