### ISSUE TITLE
ViaVersion cannot work normally in Flamecord

### ISSUE THREAD

**Issue by shiqutong** [2lstudios-mc/FlameCord#109]
ViaVersion cannot work normally in Flamecord, will lead to my every child clothing ViaVersion this plugin is loaded.

**Comment by linsaftw** [comment]
This is intended. Use ViaVersion on all Spigot (child) servers and it will work fine.

FlameCord disables ViaVersion on BungeeCord because it's a bad practice.

BungeeCord has a feature called EntityRewrite which costs a LOT of performance.
