### ISSUE TITLE
Incompatible with viaversion

### ISSUE THREAD

**Issue by Seanoo1** [2LStudios-MC/FlameCord#11]
From viaversion developer, it is flamecord side issue.
Player kicked with : 
lost connection: Internal Exception: io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0

**Comment by LinsaFTW** [comment]
> From viaversion developer, it is flamecord side issue.
> Player kicked with :
> lost connection: Internal Exception: io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0

ViaVersion doesn't go on Bungee because it crashes during attacks. You need to run it on all Bukkit servers.

**Comment by Seanoo1** [comment]
Running on all backend servers cause issue too.

**Comment by LinsaFTW** [comment]
Cant replicate. I am using ViaVersion latest on 1.8.8 server and it doesnt give any issues.

**Comment by Seanoo1** [comment]
1.12.2 paper
Try join with 1.8.9

ViaVersion - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.2.2-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.2.1-SNAPSHOT.jar
ViaRewind - https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/lastSuccessfulBuild/artifact/all/target/ViaRewind-1.5.3.jar

**Comment by LinsaFTW** [comment]
> 1.12.2 paper
> Try join with 1.8.9
> 
> Used this three jars.
> ViaVersion - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.2.2-SNAPSHOT.jar
> ViaBackwards - https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.2.1-SNAPSHOT.jar
> ViaRewind - https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/lastSuccessfulBuild/artifact/all/target/ViaRewind-1.5.3.jar

Sadly i already ran that setup and it didnt give me issues :/ Weird.
