### ISSUE TITLE
Bug with Forge (reply)

### ISSUE THREAD

**Issue by NoltoxGit** [2lstudios-mc/FlameCord#111]
Sorry, I have to keep re-opening an issue to continue the discussion x)

I tested otherwise, here is the process I did:

> I connect to the Lobby which has ViaVersion (Airplane 1.17.1) - At each connection my skin is not flat.

> I switch from the Lobby to a server in 1.18.2 without ViaVersion, my skin becomes flat

> When I go back to the Lobby my skin stays flat.

So I don't know where the problem with ViaVersion is in the story.

~ Noltox ~

**Comment by linsaftw** [comment]
If you wish to reply please use the original issue :) I will give my answer there.
