### ISSUE TITLE
Building from source fail

### ISSUE THREAD

**Issue by CasealbyOfficial** [2lstudios-mc/FlameCord#112]
I am trying to build on ubuntu server 20.04 LTS from source and this is the error i get.

> https://pastebin.com/eGDRihhR

i installed Jdk-8, git and maven

**Comment by 4drian3d** [comment]
Clearly in the error it says what you have to do: 

>*** Please tell me who you are.
> 
>Run
> 
>  git config --global user.email "you@example.com"
>  git config --global user.name "Your Name"
>
>to set your account's default identity.
>Omit --global to set the identity only in this repository.
