### ISSUE TITLE
New flamecord crasher

### ISSUE THREAD

**Issue by zDomenik12** [2LStudios-MC/FlameCord#12]
Hello, I just noticed that someone crashed my server. I just couldn't log in anymore but it didn't work in the game. The following error appeared in the console: https://pastebin.com/qBR9nrEW

I am using Flamecord version 0.4.6 and have the default config. I have also installed the 2lS antbot.

**Comment by LinsaFTW** [comment]
Hi, this is a known issue. Try removing plugins until the error gets fixed.
