### ISSUE TITLE
Flamecord server brand does not display

### ISSUE THREAD

**Issue by nhanledev** [2lstudios-mc/FlameCord#120]
I don't know if this affect the `1.7` support of FlameCord, but it looks like that the modification of [0004-1.7.x-support.patch](https://github.com/2lstudios-mc/FlameCord/blob/master/Waterfall-Proxy-Patches/0004-1.7.x-support.patch) or something at other places is changed in the latest Waterfall, so it just display the `Spigot/Paper` server name instead of `Flamecord <- Spigot/Paper` like in older version.

![image](https://user-images.githubusercontent.com/28459250/165888958-472507bd-f261-48e1-ab7a-724732daaed0.png)

**Comment by nhanledev** [comment]
I think something is wrong with version checking so it just throw an exception instead of finishing the code block

**Comment by xIsm4** [comment]
> I don't know if this affect the `1.7` support of FlameCord, but it looks like that the modification of [0004-1.7.x-support.patch](https://github.com/2lstudios-mc/FlameCord/blob/master/Waterfall-Proxy-Patches/0004-1.7.x-support.patch) or something at other places is changed in the latest Waterfall, so it just display the `Spigot/Paper` server name instead of `Flamecord <- Spigot/Paper` like in older version.
> 
> ![image](https://user-images.githubusercontent.com/28459250/165888958-472507bd-f261-48e1-ab7a-724732daaed0.png)

FlameCord just does that on the motd, not on server. (Like outgame)

**Comment by linsaftw** [comment]
Please confirm if the same happens on Waterfall.

**Comment by nhanledev** [comment]
It does not happen on Waterfall. Only on FlameCord.

**Comment by linsaftw** [comment]
Thats weird... Does it happen on a clean server in your local machine?

**Comment by linsaftw** [comment]
Can confirm same behaviour on localhost server.

**Comment by nhanledev** [comment]
Yes I tested on clean FlameCord build vs Waterfall build. If I remove the patch at https://github.com/2lstudios-mc/FlameCord/blob/2af084aaec4c53a1ed58d8819bdf5434fc7c5eab/Waterfall-Proxy-Patches/0004-1.7.x-support.patch#L2014 on line 2014 it turns back to Waterfall behavior

**Comment by linsaftw** [comment]
Yeah maybe we need to improve that line using the new methods instead of using the outdated Travertine method.
