### ISSUE TITLE
Flamecord custom cord  name 

### ISSUE THREAD

**Issue by huazhuchi** [2lstudios-mc/FlameCord#122]
Good core
Please do a new feature "Custom Core Name"
Thank you so much

**Comment by xIsm4** [comment]
> Good core Please do a new feature "Custom Core Name" Thank you so much

If I understand what you mean, it is the FlameCord brand.
That is already integrated into the MOTD system.

**Comment by huazhuchi** [comment]
No, no, what I'm talking about is that you can change the core name of flamecord in config. Flamecord will be displayed when the robot Ping the server. Request to change the custom core name of "flamecord". Thank you. Like hexacord, it has custom_ server_ name. I'm from China. I don't know the language. I'm sorry

**Comment by linsaftw** [comment]
Won't do at the moment.

**Comment by huazhuchi** [comment]
tx
