### ISSUE TITLE
I found a typo in flamecord code!

### ISSUE THREAD

**Issue by Fox2Code** [2lstudios-mc/FlameCord#123]
https://github.com/2lstudios-mc/FlameCord/blob/52117d8b70b145be5a4ed5209aa322ca69c51623/Waterfall-Proxy-Patches/0029-Antibot-System.patch#L461
Code is:
```java
    public FastChatCheck(final AddressDataManager addressDataManager) {
        this.addressDataManager = new AddressDataManager();
    }
```
But code should be:
```java
    public FastChatCheck(final AddressDataManager addressDataManager) {
        this.addressDataManager = addressDataManager;
    }
```

**Comment by Fox2Code** [comment]
https://github.com/2lstudios-mc/FlameCord/blob/52117d8b70b145be5a4ed5209aa322ca69c51623/Waterfall-Proxy-Patches/0029-Antibot-System.patch#L238
Should also be replaced by `final String addressString = AddressUtil.sanitizeAddress(iNetSocketAddress);`

**Comment by linsaftw** [comment]
Please make a PR if possible!

**Comment by linsaftw** [comment]
> https://github.com/2lstudios-mc/FlameCord/blob/52117d8b70b145be5a4ed5209aa322ca69c51623/Waterfall-Proxy-Patches/0029-Antibot-System.patch#L238
> 
> 
> Should also be replaced by `final String addressString = AddressUtil.sanitizeAddress(iNetSocketAddress);`

Why sanitize?

**Comment by Fox2Code** [comment]
> > https://github.com/2lstudios-mc/FlameCord/blob/52117d8b70b145be5a4ed5209aa322ca69c51623/Waterfall-Proxy-Patches/0029-Antibot-System.patch#L238
> > 
> > Should also be replaced by `final String addressString = AddressUtil.sanitizeAddress(iNetSocketAddress);`
> 
> Why sanitize?

Linked Waterfall patch, everything is said here:
https://github.com/PaperMC/Waterfall/blob/master/BungeeCord-Patches/0060-Strip-hostname-from-InetSocketAddress.patch
This make sure each real IP address have only 1 `AddressData` assosciated to it.

**Comment by linsaftw** [comment]
Okay!

**Comment by linsaftw** [comment]
Fixed on the PRs

**Comment by linsaftw** [comment]
Seems that util does not exist for some reason. Maybe there is no access to that dependency.
