### ISSUE TITLE
Cant connect to server with 1.18.2

### ISSUE THREAD

**Issue by madmobhunter** [2lstudios-mc/FlameCord#127]
i can connect fine with 1.8.9 - 1.18.1
with version 1.18.2 pinging the server i get :
![image](https://user-images.githubusercontent.com/13225281/167291145-9c5ee405-a26d-4c08-b389-746dff11575a.png)
connecting gives:
![image](https://user-images.githubusercontent.com/13225281/167291191-32424c4d-b61d-44c6-9eb4-dd1d7a165687.png)

i do not have viaversion on the bungee server.
i have viaversion 4.2.1 on the backend server.
i get no errors at all using waterfall #485, it shows player count and lets me connect just fine.

**Comment by linsaftw** [comment]
Works fine for me. Make sure to use latest FlameCord and latest ViaVersion on the backend server.
