### ISSUE TITLE
Remove default country blacklist

### ISSUE THREAD

**Issue by skbeh** [2lstudios-mc/FlameCord#132]
According to the following line, players from these countries will **not** able to join the server by default.
https://github.com/2lstudios-mc/FlameCord/blob/d6bbda8e53f1bae006fd8ccfcdc30fa340423c76/Waterfall-Proxy-Patches/0029-Antibot-System.patch#L798
In order to keep freedom of bungeecord community and eliminate country bias, I would be appreciate if you can remove this limit.

**Comment by linsaftw** [comment]
I don't care about where people is born or anything I just placed the countries most botnets.

Instead of pointing at us point at your country's law system that lets criminals unpunished.

**Comment by skbeh** [comment]
> I don't care about where people are born or anything I just placed the countries with the most botnets.

According to https://www.spamhaus.com/threat-map/ and https://www.spamhaus.org/statistics/botnet-cc/ which comes from the first and second results of https://www.google.com/search?q=botnet+country, there are also huge botnets in the US and India, so why just include CN and RU in the list but not US and IN?

**Comment by linsaftw** [comment]
> > I don't care about where people are born or anything I just placed the countries with the most botnets.
> 
> According to https://www.spamhaus.com/threat-map/ and https://www.spamhaus.org/statistics/botnet-cc/ which comes from the first and second results of https://www.google.com/search?q=botnet+country, there are also huge botnets in the US and India, so why just include CN and RU in the list but not US and IN?

India is blocked indeed. We ignore the US because there is where most of servers are hosted.

**Comment by skbeh** [comment]
> We ignore the US because there is where most of servers are hosted.

The firewall bans players. Where the server is hosted doesn't matter.
