### ISSUE TITLE
JustOneMore RedisBungee support

### ISSUE THREAD

**Issue by nhanledev** [2lstudios-mc/FlameCord#138]
Hello, I see that Flamecord does have a `justonemore` feature in `maxplayers`. However, it works great if you only have one bungeecord server. If you have more than 2, it starts to show for only connected players to the current bungeecord server, unlike the [JustOneMore](https://www.spigotmc.org/resources/justonemore-bungeecord.2227/) plugin that also has the support of counting total players using RedisBungee.

**Comment by linsaftw** [comment]
I think this has to be done by Redis.
