### ISSUE TITLE
Issues with commands

### ISSUE THREAD

**Issue by Ale1x** [2lstudios-mc/FlameCord#140]
Hi, When i execute any FlameCord / BungeeCord command, they have the "<>" prefix, this also happens with commands of any bungeecord plugin. 

Including examples:
![image](https://user-images.githubusercontent.com/71466131/173595563-c8b93576-634c-4ece-a631-b3f0ed5c780e.png)
![image](https://user-images.githubusercontent.com/71466131/173595660-bdd8c3f9-06b3-4316-b4f5-2213ab436e69.png)

Another issue is: when i execute proxy-side commands (like /alert or /find) they're also executed on the backend server.

Including examples:
![image](https://user-images.githubusercontent.com/71466131/173595891-1994ebc7-86f5-4f85-873c-88a8d9ad5f9a.png)

**Comment by Luccboy** [comment]
This was fixed here: https://github.com/2lstudios-mc/FlameCord/commit/6bfd1178b39f2182732269c63fd5d8da8d3b8671. It hasn't been released to McMarket but you can download it on Jenkins
