### ISSUE TITLE
SkinRestorer plugin not working on FlameCord

### ISSUE THREAD

**Issue by Ale1x** [2lstudios-mc/FlameCord#141]
Hi, [SkinRestorer](https://www.spigotmc.org/resources/skinsrestorer.2124/) plugin is not working on FlameCord, this is the error, can you maybe fix this? This plugin is really useful a lot of server use it.

Including screenshot of error:
![image](https://user-images.githubusercontent.com/71466131/173920389-6d86afdb-373e-489c-a02c-1a8986e71d8d.png)

**Comment by 4drian3d** [comment]
https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/

**Comment by Ale1x** [comment]
Working, ty
