### ISSUE TITLE
tab not compatible with flamecord

### ISSUE THREAD

**Issue by noobi04** [2lstudios-mc/FlameCord#142]
Using a plugin called "TAB" (https://www.mc-market.org/resources/20631/) which doesnt seems to be supported/compatible using FlameCord. 

The issue happens on player join which causes an exception. Since its calling a NoSuchMethodError I am assuming this happens due to FlameCord being a Waterfall fork and having different methods compared to Waterfall itself.
 
![Screenshot_30](https://user-images.githubusercontent.com/107631362/174091289-2dbd1027-7233-467c-9136-89a7a5d8f68a.png)

Seeing this being implemented in future upcoming updates would be awesome.

**Comment by 4drian3d** [comment]
https://github.com/NEZNAMY/TAB/issues/617#issuecomment-1155142747

**Comment by noobi04** [comment]
Im aware of the issue that the plugin is not supported for the latest clientversion. 
However this issue happens regardless the version. 
On Waterfall I am able to connect using 1.7 up to 1.18. Whilst using FlameCord this does only apply except for 1.7 since 1.7 doesnt have any complex tab.

**Comment by 4drian3d** [comment]
It has nothing to do with the client version, it refers to the version of Bungeecord(FlameCord) which is 1.19 (it has nothing to do with the client, I repeat again)

Waterfall has not yet been officially updated, that's why you don't have the bug, you are using a very old version of Waterfall since the current version has not yet been "released"

**Comment by noobi04** [comment]
So to resume: the error happens due to BungeeCord having a major update which requires the tab plugin to be updated to in order to work properly. And the reason why it does work on Waterfall is because they have not released their latest version. 

To properly end it. I just have to wait until the plugin gets an update, right?

**Comment by linsaftw** [comment]
> So to resume: the error happens due to BungeeCord having a major update which requires the tab plugin to be updated to in order to work properly. And the reason why it does work on Waterfall is because they have not released their latest version.
> 
> To properly end it. I just have to wait until the plugin gets an update, right?

yes
