### ISSUE TITLE
Newest Flamcord build breaking pre 1.19 BungeeGard

### ISSUE THREAD

**Issue by FirephoenixX02** [2lstudios-mc/FlameCord#143]
Since a few commits Flamecord no longer works with BungeeGuard maybe due to updating the Waterfall Upstream which i think adds 1.19 Support. This could be fixed with the newest BungeeGuard Version supporting 1.19 but sadly this version removes support for 1.8, making it no longer usable for my Server Network. So i have to use an outdated Version of both BungeeGuard and Flamecord, it would be nice if there would be a solution for this.

**Comment by 4drian3d** [comment]
Update BungeeGuard.

**Comment by FirephoenixX02** [comment]
Ok
