### ISSUE TITLE
ReadTimedOut firewalls players

### ISSUE THREAD

**Issue by linsaftw** [2lstudios-mc/FlameCord#145]

**Comment by xIsm4** [comment]
> _No description provided._

Well does not really, you do (!readTimeOut) blacklist, and a lot of cases can be firewalled then, is just better firewall ensured bad-packets like BadPacket, FastExcepcion, Overflow and that stuff.

**Comment by andreasdc** [comment]
I think NativeIoException : readAddress(..) failed: Connection reset by peer is firewalled too

**Comment by xIsm4** [comment]
#146

**Comment by andreasdc** [comment]
I have a lot of: io.netty.handler.codec.DecoderException: net.md_5.bungee.protocol.BadPacketException: No more bytes reading varint
which I think firewalls wrongly, what do you think is the cause?

**Comment by linsaftw** [comment]
> > Can't reproduce this error. Running FlameCord 1.0.4 and ViaVersion (Latest from Spigot).
> 
> You can't reproduce your error or mine? I'm using slightly older version.

Update then. Not updating = having bugs.

**Comment by andreasdc** [comment]
I have to review what did change, I saw something with geoip blockage and 1.19 errors, is that true?

**Comment by linsaftw** [comment]
> I have to review what did change, I saw something with geoip blockage and 1.19 errors, is that true? Also can you merge with upstream?

Instead of asking test by yourself, it all depends on your server configuration if FlameCord fits your needs or not. I've never had issues with 1.19, only specific plugins have this problem.

**Comment by andreasdc** [comment]
> > I have to review what did change, I saw something with geoip blockage and 1.19 errors, is that true? Also can you merge with upstream?
> 
> Instead of asking test by yourself, it all depends on your server configuration if FlameCord fits your needs or not. I've never had issues with 1.19, only specific plugins have this problem.

Can you merge with upstream?

**Comment by linsaftw** [comment]
> > > I have to review what did change, I saw something with geoip blockage and 1.19 errors, is that true? Also can you merge with upstream?
> > 
> > 
> > Instead of asking test by yourself, it all depends on your server configuration if FlameCord fits your needs or not. I've never had issues with 1.19, only specific plugins have this problem.
> 
> Can you merge with upstream?

I always do.

**Comment by linsaftw** [comment]
This issue still happens but seems none of my fixes have worked to fix it. I will have this in mind but I will close it for now because everything is uncertain for this.

**Comment by andreasdc** [comment]
So time out still firewalls players?
Bungee released new patches couple days ago.

**Comment by linsaftw** [comment]
> So time out still firewalls players? Bungee released new patches couple days ago.

Yes I made debug and even if i check that the exception is not timeout it blacklists anyways.
