### ISSUE TITLE
Players are randomly kicked from the subserver without doing anything.

### ISSUE THREAD

**Issue by byNixo** [2lstudios-mc/FlameCord#149]
Players are kicked off the server either individually or en masse. They are sent to the lobby (probably entirely from the server) since I have the BungeeKick plugin.

Is this due to a wrong attitude?

**Comment by linsaftw** [comment]
Maybe invalid packet? Can you please send the error in the spigot server that they got kicked from?

**Comment by xIsm4** [comment]
> Players are kicked off the server either individually or en masse. They are sent to the lobby (probably entirely from the server) since I have the BungeeKick plugin.
> 
> Is this due to a wrong attitude?

Also for decoder debug you need to use this startup flag -Dwaterfall.packet-decode-logging=true

**Comment by byNixo** [comment]
> 

In the Start.sh file of my subserver?

**Comment by linsaftw** [comment]
No response.
