### ISSUE TITLE
Problem with viaversion when ip is firewalled

### ISSUE THREAD

**Issue by DieuHades2** [2LStudios-MC/FlameCord#15]
![image](https://user-images.githubusercontent.com/64600191/110092776-428e7500-7d9a-11eb-8a88-1157c7b87746.png)
It cause a InvocationTargetException with ViaVersion.
It spam the console and it could be a bypass for crashing/laging FlameCord

**Comment by LinsaFTW** [comment]
Don't run ViaVersion in BungeeCord as it can be crashed by bot attacks.
