### ISSUE TITLE
UDP query port just dies

### ISSUE THREAD

**Issue by Pijanista** [2lstudios-mc/FlameCord#152]
Hello,

On flamecord after receiving the "malicious" query the UDP port just dies while it seems that at waterfall, everything is fine.

This is the log before UDP dies:

[09:59:00 WARN]: Query - Incorrect magic!: /149.202.80.71:36372

After it happens, UDP is not working anymore.

[root@bungee test]# netstat -tulnp | grep 25565
tcp6       0      0 xxx:25565     :::*                    LISTEN      4017938/java
udp6       0      0 xxx:25565     :::*                                137687/java
[root@bungee test]#
[root@bungee test]#
[root@bungee test]# netstat -tulnp | grep 25565
tcp6       0      0 xxx:25565     :::*                    LISTEN      4017938/java
udp6       0      0 xxx:25565     :::*                                137687/java
[root@bungee test]#
**Died here**
[root@bungee test]#
[root@bungee test]# netstat -tulnp | grep 25565
tcp6       0      0 xxx:25565     :::*                    LISTEN      4017938/java
[root@bungee test]#
[root@bungee test]#
[root@bungee test]# netstat -tulnp | grep 25565
tcp6       0      0 xxx:25565     :::*                    LISTEN      4017938/java

**Comment by Pijanista** [comment]
https://github.com/2lstudios-mc/FlameCord/blob/master/Waterfall-Proxy-Patches/0009-Close-connections-Don-t-flush-if-not-necessary.patch

             bungee.getLogger().log( Level.WARNING, "Query - Incorrect magic!: {0}", msg.sender() );
+            // FlameCord - Close on incorrect magic
+            ctx.close();

As this is UDP, ctx.close will do that, as there are actually no connections.
Should be left as it's on Bungee/Water

**Comment by xIsm4** [comment]
> https://github.com/2lstudios-mc/FlameCord/blob/master/Waterfall-Proxy-Patches/0009-Close-connections-Don-t-flush-if-not-necessary.patch
> 
> ```
>              bungee.getLogger().log( Level.WARNING, "Query - Incorrect magic!: {0}", msg.sender() );
> +            // FlameCord - Close on incorrect magic
> +            ctx.close();
> ```
> 
> As this is UDP, ctx.close will do that, as there are actually no connections. Should be left as it's on Bungee/Water

It only closes when the exception happens, so its caused by something.

**Comment by linsaftw** [comment]
Why is incorrect magic happening tho?
