### ISSUE TITLE
Blacklist Countries

### ISSUE THREAD

**Issue by OnqKolev** [2lstudios-mc/FlameCord#157]
When i add every country in the list, expect my country, i get this error: 

NullPointerExeption: null @ dev.2lstudios.antibot.CountyCheck:97.

**Comment by andreasdc** [comment]
Wrong country code?

**Comment by Claniel** [comment]
- AF
    - AX
    - AL
    - DZ
    - AS
    - AD
    - AO
    - AI
    - AQ
    - AG
    - AR
    - AM
    - AU
    - AT
    - AZ
    - BS
    - BH
    - BD
    - BB
    - BY
    - BE
    - BZ
    - BJ
    - BM
    - BT
    - BO
    - BQ
    - BA
    - BW
    - BV
    - BR
    - IO
    - BN
    - BF
    - BI
    - CV
    - KH
    - CM
    - CA
    - KY
    - CF
    - TD
    - CL
    - CN
    - CX
    - CC
    - CO
    - KM
    - CG
    - CD
    - CK
    - CR
    - CI
    - HR
    - CU
    - CW
    - CY
    - CZ
    - DK
    - DJ
    - DM
    - DO
    - EC
    - EG
    - SV
    - GQ
    - ER
    - EE
    - SZ
    - ET
    - FK
    - FO
    - FJ
    - FI
    - FR
    - GF
    - PF
    - TF
    - GA
    - GM
    - GE
    - DE
    - GH
    - GI
    - GR
    - GL
    - GD
    - GP
    - GU
    - GT
    - GG
    - GN
    - GW
    - GY
    - HT
    - HM
    - VA
    - HN
    - HK
    - HU
    - IS
    - IN
    - ID
    - IR
    - IQ
    - IE
    - IM
    - IL
    - IT
    - JM
    - JP
    - JE
    - JO
    - KZ
    - KE
    - KI
    - KP
    - KR
    - KW
    - KG
    - LA
    - LV
    - LB
    - LS
    - LR
    - LY
    - LI
    - LT
    - LU
    - MO
    - MG
    - MW
    - MY
    - MV
    - ML
    - MT
    - MH
    - MQ
    - MR
    - MU
    - YT
    - MX
    - FM
    - MD
    - MC
    - MN
    - ME
    - MS
    - MA
    - MZ
    - MM
    - NA
    - NR
    - NP
    - NL
    - NC
    - NZ
    - NI
    - NE
    - NG
    - NU
    - NF
    - MK
    - MP
    - OM
    - PK
    - PW
    - PS
    - PA
    - PG
    - PY
    - PE
    - PH
    - PN
    - PL
    - PT
    - PR
    - QA
    - RE
    - RO
    - RU
    - RW
    - BL
    - SH
    - KN
    - LC
    - MF
    - PM
    - VC
    - WS
    - SM
    - ST
    - SA
    - SN
    - RS
    - SC
    - SL
    - SG
    - SX
    - SK
    - SI
    - SB
    - SO
    - ZA
    - GS
    - SS
    - ES
    - LK
    - SD
    - SR
    - SJ
    - SE
    - CH
    - SY
    - TW
    - TJ
    - TZ
    - TH
    - TL
    - TG
    - TK
    - TO
    - TT
    - TN
    - TR
    - TM
    - TC
    - TV
    - UG
    - UA
    - AE
    - GB
    - US
    - UM
    - UY
    - UZ
    - VU
    - VE
    - VN
    - VG
    - VI
    - WF
    - EH
    - YE
    - ZM
    - ZW

**Comment by Claniel** [comment]
> Wrong country code?
These are the country codes in the yml file, i don't see any problem with them

- AF
- AX
- AL
- DZ
- AS
- AD
- AO
- AI
- AQ
- AG
- AR
- AM
- AU
- AT
- AZ
- BS
- BH
- BD
- BB
- BY
- BE
- BZ
- BJ
- BM
- BT
- BO
- BQ
- BA
- BW
- BV
- BR
- IO
- BN
- BF
- BI
- CV
- KH
- CM
- CA
- KY
- CF
- TD
- CL
- CN
- CX
- CC
- CO
- KM
- CG
- CD
- CK
- CR
- CI
- HR
- CU
- CW
- CY
- CZ
- DK
- DJ
- DM
- DO
- EC
- EG
- SV
- GQ
- ER
- EE
- SZ
- ET
- FK
- FO
- FJ
- FI
- FR
- GF
- PF
- TF
- GA
- GM
- GE
- DE
- GH
- GI
- GR
- GL
- GD
- GP
- GU
- GT
- GG
- GN
- GW
- GY
- HT
- HM
- VA
- HN
- HK
- HU
- IS
- IN
- ID
- IR
- IQ
- IE
- IM
- IL
- IT
- JM
- JP
- JE
- JO
- KZ
- KE
- KI
- KP
- KR
- KW
- KG
- LA
- LV
- LB
- LS
- LR
- LY
- LI
- LT
- LU
- MO
- MG
- MW
- MY
- MV
- ML
- MT
- MH
- MQ
- MR
- MU
- YT
- MX
- FM
- MD
- MC
- MN
- ME
- MS
- MA
- MZ
- MM
- NA
- NR
- NP
- NL
- NC
- NZ
- NI
- NE
- NG
- NU
- NF
- MK
- MP
- OM
- PK
- PW
- PS
- PA
- PG
- PY
- PE
- PH
- PN
- PL
- PT
- PR
- QA
- RE
- RO
- RU
- RW
- BL
- SH
- KN
- LC
- MF
- PM
- VC
- WS
- SM
- ST
- SA
- SN
- RS
- SC
- SL
- SG
- SX
- SK
- SI
- SB
- SO
- ZA
- GS
- SS
- ES
- LK
- SD
- SR
- SJ
- SE
- CH
- SY
- TW
- TJ
- TZ
- TH
- TL
- TG
- TK
- TO
- TT
- TN
- TR
- TM
- TC
- TV
- UG
- UA
- AE
- GB
- US
- UM
- UY
- UZ
- VU
- VE
- VN
- VG
- VI
- WF
- EH
- YE
- ZM
- ZW

**Comment by andreasdc** [comment]
You can try adding 1 by 1, probably there isn't a check for wrong country code.

**Comment by Claniel** [comment]
> You can try adding 1 by 1, probably there isn't a check for wrong country code.

I checked all the countries and added а new ones and I still have the same error

**Comment by andreasdc** [comment]
Post the full error

**Comment by Claniel** [comment]
> Post the full error

There is no error in the console,  but when i try to connect to the server, this pops up NullPointerExeption: null @ dev.2lstudios.antibot.CountyCheck:97

**Comment by andreasdc** [comment]
Try with just default list
"CN", "HK", "RU", "IN", "TH", "ID", "DZ", "VN", "IR", "PK"

**Comment by Claniel** [comment]
> Try with just default list "CN", "HK", "RU", "IN", "TH", "ID", "DZ", "VN", "IR", "PK"

Did it, but still the same. Not letting me in with the same message

**Comment by andreasdc** [comment]
Try disabling country check and wait for developers to respond

**Comment by mitko1337** [comment]
The thing is that the server is being attacked and ddos-ed, and in the second i turn of the country check it explodes :D

> Try disabling country check and wait for developers to respond

**Comment by mitko1337** [comment]
Im the server developer if ur wondering

**Comment by andreasdc** [comment]
You should get another antiddos

**Comment by xIsm4** [comment]
> Wrong country code?

I don't think that will throw an NPE if doesn't find the country, mostly.

**Comment by linsaftw** [comment]
Fixed in [0ca7776](https://github.com/2lstudios-mc/FlameCord/commit/0ca7776b9a55dfac524386a318f7693f3d506638)
