### ISSUE TITLE
Firewall messages never show

### ISSUE THREAD

**Issue by andreasdc** [2lstudios-mc/FlameCord#158]
Firewall messages like antibot_ratelimit are never shown, you only get 'Disconnected' message, but be careful with that as this needs extra packet to be sent.

**Comment by linsaftw** [comment]
> Firewall messages like antibot_ratelimit are never shown, you only get 'Disconnected' message, but be careful with that as this needs extra packet to be sent.

Lets not do it then.

**Comment by andreasdc** [comment]
But the packet are still being sent, it just doesn't appear sometimes.
