### ISSUE TITLE
Suggestion for the ServerSwitchEvent

### ISSUE THREAD

**Issue by HakanGulgen** [2lstudios-mc/FlameCord#16]
Hi, my suggestion is do not call ServerSwitchEvent if it's not a server switch. (This event is called every player login)

**Comment by linsaftw** [comment]
Hi, why not making this on Bungee instead? This way everyone in the community gets the update Bungee -> Waterfall -> Travertine -> FlameCord

**Comment by Luccboy** [comment]
That's true, I will close my PR
