### ISSUE TITLE
DecoderException on login

### ISSUE THREAD

**Issue by Whitescan** [2lstudios-mc/FlameCord#160]
Just downloaded the latest version of FlameCord from BuildByBit.
When people log into the server, not much info is given.

Server Side: https://mcpaste.io/3fdd256fe5b60159
Client Side: https://prnt.sc/7Pj1gm5_1kV8

Latest Version. Could not quite pinpoint the issue as the stacktrace is just not appearing anywhere. I also checked client logs, nothing.

**Comment by andreasdc** [comment]
What client version?

**Comment by Whitescan** [comment]
Tested replacing FlameCord with Waterfall, worked fine. Went right to the lobby without issues. Changing back to FlameCord makes the problem appear again.

**Comment by Whitescan** [comment]
> What client version?

Latest Version 1.19.2

**Comment by Whitescan** [comment]
> > > What client version?
> > 
> > 
> > Latest Version 1.19.2
> 
> There is problem with 1.19+, use older build and be patient for the fix.

Alr ty

**Comment by xIsm4** [comment]
> Just downloaded the latest version of FlameCord from BuildByBit. When people log into the server, not much info is given.
> 
> Server Side: https://mcpaste.io/3fdd256fe5b60159 Client Side: https://prnt.sc/7Pj1gm5_1kV8
> 
> Latest Version. Could not quite pinpoint the issue as the stacktrace is just not appearing anywhere. I also checked client logs, nothing.

I did not see this issue, I knew since I saw the commit that this was not going to work. Waterfall removed the byte limits for 1.19 because it was sending more information than others. You can simply remove the patch or use an earlier version than this one. I have already notified LinsaFTW, if he can't I will make the pull request.

**Comment by nhanledev** [comment]
Just use version 1.1.1, recent update of Flamecord broke it

**Comment by JosGCS** [comment]
I have the same problem with 1.19.2 players, please fix asap :(

**Comment by andreasdc** [comment]
Use any version before 12.09.2022

**Comment by linsaftw** [comment]
Fixed!
