### ISSUE TITLE
Merging Lightfall patches in favor of Forge (1.13+) support

### ISSUE THREAD

**Issue by wellnesscookie** [2lstudios-mc/FlameCord#167]
**Issue:**
Currently, there is no way for Forge (1.13+) users to connect to modern proxy software whilst properly working. Archlight (server software for forge + spigot/bukkit) has forked Waterfall and made their own changes in order for Archlight to be able to successfully handshake and enable players to connect through proxy.

Archlight (server) software: https://github.com/IzzelAliz/Arclight
Lightfall (proxy) software: https://github.com/ArclightPowered/lightfall

The workaround from sides of BungeeCord, Velocity and Forge is apparently not to be seen, as they are apparently required to sit for one table and agree on some things, because it requires both sides for a solution to pop. The discussion can be seen here: https://github.com/PaperMC/Velocity/pull/690

**Feature request:**
As flamecord users, we'd not love to downgrade to a Lightfall only for this to work, but rather see Lightfall patches alongside with FlameCord ones, so that our players can join through flamecord to our both normal and forge servers.

**Comment by xIsm4** [comment]
I'll give you a simple explanation why this is not good. First of all, it would totally break the structure of the basic "antibot" system that FlameCord comes with, creating another bridge for the packets to be handled by the MOD. That's another point, relying on a mod makes the proxy no longer functional for most players.

The problem with modern-forge is its rare protocol that currently cannot be integrated with a proxy without breaking other things or relying on others

> **Issue:** Currently, there is no way for Forge (1.13+) users to connect to modern proxy software whilst properly working. Archlight (server software for forge + spigot/bukkit) has forked Waterfall and made their own changes in order for Archlight to be able to successfully handshake and enable players to connect through proxy.
> 
> Archlight (server) software: https://github.com/IzzelAliz/Arclight Lightfall (proxy) software: https://github.com/ArclightPowered/lightfall
> 
> The workaround from sides of BungeeCord, Velocity and Forge is apparently not to be seen, as they are apparently required to sit for one table and agree on some things, because it requires both sides for a solution to pop. The discussion can be seen here: [PaperMC/Velocity#690](https://github.com/PaperMC/Velocity/pull/690)
> 
> **Feature request:** As flamecord users, we'd not love to downgrade to a Lightfall only for this to work, but rather see Lightfall patches alongside with FlameCord ones, so that our players can join through flamecord to our both normal and forge servers.

**Comment by linsaftw** [comment]
Tried and doesn't seem to work properly.
