### ISSUE TITLE
The message "fallback_kick" does not show information from the args. 

### ISSUE THREAD

**Issue by PalmTamino** [2lstudios-mc/FlameCord#168]
I use the standard messages.yml nothing changed. 

To reproduce:
1 Try to connect to a server which is offline via /server
2 Receive error message without information.

![grafik](https://user-images.githubusercontent.com/36358673/200177798-26462cca-c7c7-4299-a224-a0a7c3caa6ef.png)
@linsaftw

**Comment by linsaftw** [comment]
This is not a bug, it's an option. We will remove this option because it doesn't bring anything good. Thanks.

**Comment by linsaftw** [comment]
set "logger.detailed-connect-errors" to true.

**Comment by PalmTamino** [comment]
![grafik](https://user-images.githubusercontent.com/36358673/201869628-d1febef2-4296-4844-a2de-b19af1a7ff17.png)
Still not showing @linsaftw

**Comment by linsaftw** [comment]
Seems waterfall is responsible of this. Fixing.

**Comment by linsaftw** [comment]
Try latest 1.1.9

**Comment by PalmTamino** [comment]
> Try latest 1.1.9

You mean latest flamecord? Or a new update of the backend server?

**Comment by linsaftw** [comment]
> > Try latest 1.1.9
> 
> You mean latest flamecord? Or a new update of the backend server?

Latest FlameCord.
