### ISSUE TITLE
I wasn't able to join the network for a small amount of time

### ISSUE THREAD

**Issue by PalmTamino** [2lstudios-mc/FlameCord#170]
https://paste.gg/p/anonymous/c1c874f37f884d269e85aced29efd3c3

This is the stacktrace, if it helps you, nice! If not, just close this issue.

**Comment by linsaftw** [comment]
Please make sure to read the errors before reporting.

"Too many connections to mojang.net"

This means you are authenticating too many accounts with Mojang. This error is not related to FlameCord but with Mojang authentication system which doesn't allow the amount of traffic you have.

**Comment by andreasdc** [comment]
What's the limit on hasJoined request?
