### ISSUE TITLE
stats command

### ISSUE THREAD

**Issue by S2YM00N** [2lstudios-mc/FlameCord#178]
/flamecord stats like aegis
CPS
Joins
pings and server ping

**Comment by xIsm4** [comment]
> /flamecord stats like aegis CPS Joins pings and server ping

I think this is better and removing logs of the antibot from console, the comumption is ass.

**Comment by linsaftw** [comment]
> > /flamecord stats like aegis CPS Joins pings and server ping
> 
> I think this is better and removing logs of the antibot from console, the comumption is ass.

The logs will be nerfed to not lag the server

**Comment by linsaftw** [comment]
Done
