### ISSUE TITLE
Modules break RedisBungee overrides

### ISSUE THREAD

**Issue by andreasdc** [2lstudios-mc/FlameCord#181]
As in the title. https://github.com/ProxioDev/RedisBungee/issues/61

**Comment by linsaftw** [comment]
So, you want us to remove the FlameCord module system. How about redis instead of making overrides it makes it's own commands?

**Comment by andreasdc** [comment]
Maybe it should register modules before loading the plugins?

**Comment by linsaftw** [comment]
> Maybe it should register modules before loading the plugins?

You are right.

**Comment by andreasdc** [comment]
By the way modules folder is not used anymore right?

**Comment by linsaftw** [comment]
> By the way modules folder is not used anymore right?

Right

**Comment by linsaftw** [comment]
Fixed in latest update
