### ISSUE TITLE
FlameCord breaks chat link interaction

### ISSUE THREAD

**Issue by Whitescan** [2lstudios-mc/FlameCord#182]
Links in chat are no longer clickable.

So I made a REALLY ANNOYING binary search on my whole network (first the purpur instance then the proxy) since I did not change anything I could think of that would break it.

When I ran the server without any plugins I came to the conclusion that FlameCord must be breaking it.
Replaced FlameCord with Waterfall and everything started to work again.

I'm running the currently newest version of Minecraft (1.19.3) and also the latest version of FlameCord (1.2.4).

First noticed the issue while clicking the [gsit ](https://www.spigotmc.org/resources/gsit-modern-sit-seat-and-chair-lay-and-crawl-plugin-1-13-x-1-19-x.62325/) update notification link.

**Comment by andreasdc** [comment]
It was removed in one of the latest updates. It was intentional, but may break clickable links. Use version before 31.12.2022 or wait for the fix. @linsaftw

**Comment by PalmTamino** [comment]
> It was removed in one of the latest updates. It was intentional, but may break clickable links. Use version before 31.12.2022 or wait for the fix. @linsaftw

Why do they intentionally create a bug without saying it??

**Comment by andreasdc** [comment]
The bug is not intentional I suppose.

**Comment by linsaftw** [comment]
> > It was removed in one of the latest updates. It was intentional, but may break clickable links. Use version before 31.12.2022 or wait for the fix. @linsaftw
> 
> Why do they intentionally create a bug without saying it??

Because it uses up performance during bot attacks. I will probably make an alterntive method with no usage instead of breaking the official one.

**Comment by PalmTamino** [comment]
> > > It was removed in one of the latest updates. It was intentional, but may break clickable links. Use version before 31.12.2022 or wait for the fix. @linsaftw
> > 
> > 
> > Why do they intentionally create a bug without saying it??
> 
> Because it uses up performance during bot attacks. I will probably make an alterntive method with no usage instead of breaking the official one.

That sounds good, but please make it so that Plugins automatically use your alternative method, not that we then still have this error.

**Comment by Whitescan** [comment]
For the meantime, can't the server only disable client packets? If the server is sending it, just allow it?

**Comment by linsaftw** [comment]
> For the meantime, can't the server only disallow it for clients? If the server is sending it, just allow it?

For the meantime nothing can be done. You have to wait.



> > > > It was removed in one of the latest updates. It was intentional, but may break clickable links. Use version before 31.12.2022 or wait for the fix. @linsaftw
> > > 
> > > 
> > > Why do they intentionally create a bug without saying it??
> > 
> > 
> > Because it uses up performance during bot attacks. I will probably make an alterntive method with no usage instead of breaking the official one.
> 
> That sounds good, but please make it so that Plugins automatically use your alternative method, not that we then still have this error.

It's only for the FlameCord antibot.

**Comment by xIsm4** [comment]
> > > It was removed in one of the latest updates. It was intentional, but may break clickable links. Use version before 31.12.2022 or wait for the fix. @linsaftw
> > 
> > 
> > Why do they intentionally create a bug without saying it??
> 
> Because it uses up performance during bot attacks. I will probably make an alterntive method with no usage instead of breaking the official one.

Performance isn't all. You need to give stability and scalability with external software.

**Comment by linsaftw** [comment]
Fixed in latest update.
