### ISSUE TITLE
Accounts Check Bypass

### ISSUE THREAD

**Issue by vhcrack** [2lstudios-mc/FlameCord#184]
Add the ability to whitelist IPs, specifically for the accounts section of the config. Need this since I'm using a 2nd proxy that breaks when IPs get forwarded.

**Comment by linsaftw** [comment]
Very good addition to the already existing "hardcoded blacklist" of 127.0.0.1.

**Comment by linsaftw** [comment]
Done.

**Comment by vhcrack** [comment]
> Done.

Works great! However, it doesn't allow me to bypass the account limit for certain IPs causing people using a proxy I set up to be disconnected.

**Comment by linsaftw** [comment]
Done
