### ISSUE TITLE
Libdeflate Compression

### ISSUE THREAD

**Issue by linsaftw** [2lstudios-mc/FlameCord#188]
This will improve performance during packet processing.

**Comment by linsaftw** [comment]
Not able to implement.

**Comment by andreasdc** [comment]
Maybe this will help https://github.com/CobbleSword/NachoSpigot/commit/94fc540c187b92cc6347bb05fb540f8bc65eabc4

**Comment by linsaftw** [comment]
I will give it another try.

**Comment by linsaftw** [comment]
What I don't understand is how to integrate this on the BungeeCord decompression/compression system which alternates depending on the support.

**Comment by xIsm4** [comment]
> What I don't understand is how to integrate this on the BungeeCord decompression/compression system which alternates depending on the support. I still have no clue on how to implement this.

Why you don't speak with me on discord?

**Comment by linsaftw** [comment]
> > What I don't understand is how to integrate this on the BungeeCord decompression/compression system which alternates depending on the support. I still have no clue on how to implement this.
> 
> Why you don't speak with me on discord?

Sure

**Comment by xIsm4** [comment]
> Maybe this will help [CobbleSword/NachoSpigot@94fc540](https://github.com/CobbleSword/NachoSpigot/commit/94fc540c187b92cc6347bb05fb540f8bc65eabc4) & https://github.com/PaperMC/Paper/blob/master/patches/server/0726-Use-Velocity-compression-and-cipher-natives.patch

https://github.com/2lstudios-mc/FlameCord/pull/196/files

**Comment by andreasdc** [comment]
Nice work ❤️
