### ISSUE TITLE
Cannot set online mode in PreLoginEvent

### ISSUE THREAD

**Issue by kyngs** [2lstudios-mc/FlameCord#190]
On flamecord-based forks, setting online mode on the PendingConnection is not possible. When I attempt to do so, I get an IllegalStateException.
However, this works just fine on bungee/waterfall, therefore I consider this to be a bug.
I've traced the issue back to this patch: https://github.com/2lstudios-mc/FlameCord/blob/f91f82aff32278f748c564c8074b800a84ccc0c5/Waterfall-Proxy-Patches/0028-InitialHandler-Processing-State.patch#L59-L65
Is there any reason to introduce this incompatibility with bungee API?

**Comment by linsaftw** [comment]
No. Fixing very soon.

**Comment by linsaftw** [comment]
Fixed
