### ISSUE TITLE
Add Bot-Attack detection event to API

### ISSUE THREAD

**Issue by wellnesscookie** [2lstudios-mc/FlameCord#192]
It would be cool to listen to an event that triggers once the attack has been detected. We could then make plugins that do some preventive stuff, like turning PvP off in case some players get disconnected, etc.

**EDIT:** And for users that are not familiar with coding, maybe a list of commands to execute in config would also be welcome.

**Comment by linsaftw** [comment]
So, if connections > configuredValue you want it to run an event?

**Comment by linsaftw** [comment]
Will not do. You can always get the ammount of connections received from the API. (FlameCord.getInstance())
