### ISSUE TITLE
Fix placeholders inside of proxy PROTOCOL NAME

### ISSUE THREAD

**Issue by TheJoshue** [2lstudios-mc/FlameCord#193]
the title explains (it's inside of `flamecord.yml`)

related to `%onlineplayers%` and `%maxplayers%` placeholders

*NOTE: i did not check if they are broken (placeholders) at `sample` for motds, will check later/next days

![image](https://user-images.githubusercontent.com/56804505/214288135-366f3b91-1347-4c7b-8d1d-ff509f32309b.png)

**Comment by linsaftw** [comment]
Done
