### ISSUE TITLE
Add whitelisted-usernames to antibot.accounts module at flamecord.yml config

### ISSUE THREAD

**Issue by TheJoshue** [2lstudios-mc/FlameCord#194]
read title + here is example:
- `limit` for accounts antibot module here (`flamecord.yml`) is `2`
- there is a `accounts.whitelisted-users` section where we define the usernames that aren't counted from 1 ip address
- let's add `LinsaFTW` to the list for example
(given that the limit is `2`, that amount of player from the same IP can join)
- let's say that `Player1` and `Player2` joined the server (from the same IP)
- now the `Player3` is trying to join the server from the same IP as `Player1` and `Player2` but he is indeed DENIED to join
- however, let's say that `LinsaFTW` username is trying to join the server (same ip as `Player1` and `Player2`) - he indeed CAN JOIN because he is on the whitelist
![image](https://user-images.githubusercontent.com/56804505/214288381-0ab32f1b-1d5d-456e-9262-f22d95a6f1b8.png)

```yml
antibot:
  accounts:
    enabled: true
    firewall: true
    limit: 2
    log: true
    whitelisted-users:
    - TheJoshua
    - LinsaFTW
```
and let's say that `Player1` and `Player2` again joined from the same ip (same PC)
and then on that same PC there are `TheJoshua` and `LinsaFTW` trying to join the server - they will indeed join the server

same applies even if the `whitelisted-users` list has a lot of more usernames joining from different IP addresses, __**it just doesn't count that player for the current amount of connected clients from the same IP**__

**Comment by linsaftw** [comment]
Done
