### ISSUE TITLE
After the limit for (antibot's module) "accounts" is reached, the next client that joins from the same ip gets non-customizable kick message

### ISSUE THREAD

**Issue by TheJoshue** [2lstudios-mc/FlameCord#195]
In relation to newly added `whitelist` of usernames at `antibot.accounts` in flamecord.yml (#194)

example:
- limit is 2
- 2 players join from same PC (IP address)
- when the 3rd player joins, he gets this kick message:
![image](https://user-images.githubusercontent.com/56804505/214708862-081e1994-ef8f-408c-9f79-d3a69c51b901.png)

I think that user should receive message defined in `messages.yml` at message "antibot_accounts"

**Comment by linsaftw** [comment]
Invalid. The check already shows a message when the limit is reached. This is not FlameCord kicking.
