### ISSUE TITLE
Error switching servers

### ISSUE THREAD

**Issue by HiJackerRZ** [2lstudios-mc/FlameCord#198]
When i use version 1.3.4 i can connect to lobby but from there I can't go on any other servers. Is says: The server you were previously on went down,you have been connected to a fallback server. , This only happen when I am on a premium account,cracked ones and bedrock accounts seems to work!

**Comment by linsaftw** [comment]
Update: Not happening on test server with online mode enabled. Further looking into this.

**Comment by linsaftw** [comment]
Update: JPremium is not causing the issue.

**Comment by linsaftw** [comment]
Update: SternalBoard is not causing the issue.
Update: SafeNet is not causing the issue.
Update: Network Compression Threshold is not causing the issue.

**Comment by linsaftw** [comment]
Update: NAntibot is not causing the issue.

**Comment by linsaftw** [comment]
Update: Pterodactyl is not causing the issue.

**Comment by linsaftw** [comment]
No idea of what is was. Removing Libdeflate fixed the issue.
