### ISSUE TITLE
Query not working on FlameCord

### ISSUE THREAD

**Issue by TomLewis** [2lstudios-mc/FlameCord#20]
Moved from waterfall to FlameCord today as Waterfall was getting crashed.
Query no longer, has FlameCord disabled query?

Im aware that Query can be attacked, but I have it firewalled off to only allow certain servers to query the server.

**Comment by tomikcz987** [comment]
I have the same problem after updating to the latest version

**Comment by TomLewis** [comment]
@tomikcz987 This is my first time using Flamecord, did Query work previously in other versions?

**Comment by tomikcz987** [comment]
> 
> 
> @tomikcz987 This is my first time using Flamecord, did Query work previously in other versions?

yes

**Comment by linsaftw** [comment]
Hi, i removed the checks on query to fix this issue :) It will be fixed in the next update. I will upload it here on the releases section.
