### ISSUE TITLE
Compiling Error No pom.xml

### ISSUE THREAD

**Issue by GDMgmer3992** [2lstudios-mc/FlameCord#200]
The goal you specified requires a project to execute but there is no POM in this directory (/home/ouiping/FlameCord). Please verify you invoked Maven from the correct directory.

**Comment by linsaftw** [comment]
To compile you need to ask us for the pom.xml via Discord. Only buyers can access to this file.

**Comment by BetTD** [comment]
What is the point of making the project open-source, then?

**Comment by ItsLachy** [comment]
Feel free to download a patched version here:
https://ci.bettd.me/job/other/job/FlameCord/59/

**Comment by linsaftw** [comment]
It will be open source again. I am against this, but since the hate against this is so much I have to go back. You win. But guys, if the projects enters bankruptcy remember what we talked today. I don't trust this model at all.
