### ISSUE TITLE
Support DynDNS

### ISSUE THREAD

**Issue by Fox2Code** [2lstudios-mc/FlameCord#204]
I was asked to make this issue.

https://github.com/SpigotMC/BungeeCord/compare/master...vtroxi:BungeeCord:master
https://github.com/vtroxi/BungeeCord

Quote from source:
"BungeeCord initially resolves the underlying IP of a server's hostname assuming that it does not change afterwards.
This leads to servers becoming unreachable, after the dynamic IP address has changed."

While there should be no harm in enabling it by default, I think making this feature toggleable should be best.

Also `updateServerIPs()` should not be called on connection I think, or at least heavelly rate limited if kept as-is.  
(Like only allowing one `updateServerIPs()` call per minute.)

**Comment by linsaftw** [comment]
Tested, seems to work perfectly fine.
