### ISSUE TITLE
Optimize channel close

### ISSUE THREAD

**Issue by andreasdc** [2lstudios-mc/FlameCord#207]
Hey is it possible to optimize closing channel a bit? I think it takes the most resources during the attack (after the bot is blacklisted or instantly blocked, by name for example).
![image](https://user-images.githubusercontent.com/82218780/227391617-cf0cbd79-7964-481e-8a3d-b146f963f558.png)
Opening channel too:
![image](https://user-images.githubusercontent.com/82218780/227393482-cd6a5c32-21e5-425c-a74a-f150cde78318.png)

**Comment by linsaftw** [comment]
Closing is impossible to fix, as the usage is from .so calls.
The other one is discussable. Let me check.

**Comment by andreasdc** [comment]
> Closing is impossible to fix, as the usage is from .so calls. The other one is discussable. Let me check.

I think removing bungee's throttle system will help a little too, I don't know if the similar one is in flamecord right now, but using 2 at once is not so good.

**Comment by linsaftw** [comment]
> > Closing is impossible to fix, as the usage is from .so calls. The other one is discussable. Let me check.
> 
> I think removing bungee's throttle system will help a little too, I don't know if the similar one is in flamecord right now, but using 2 at once is not so good.

You can just set it to -1 I think. Anyways, next version will have less usage.

**Comment by linsaftw** [comment]
Can you please expand the throttle part? I will see if I can optimize without removing it.

**Comment by andreasdc** [comment]
I think just using this cache is slow.
![image](https://user-images.githubusercontent.com/82218780/227402558-cd5aac5a-7a22-4558-b218-53a4ebb972ee.png)

**Comment by linsaftw** [comment]
> I think just using this cache is slow. ![image](https://user-images.githubusercontent.com/82218780/227402558-cd5aac5a-7a22-4558-b218-53a4ebb972ee.png)

Yep. Going to do something about it.

**Comment by linsaftw** [comment]
Are you in the 2LStudios DC?

**Comment by andreasdc** [comment]
You mena with the latest 2 patches? I did optimizations to the initChannel method pretty similar, I reached around 0.5% improvement, the one with sanitizing address I will test later as I don't want to risk it being broken atm.

**Comment by linsaftw** [comment]
> You mean with the latest 2 patches? I did optimizations to the initChannel method pretty similar, I reached around 0.5% improvement, the one with sanitizing address I will test later as I don't want to risk it being broken atm.

Tested and seems not broken. Removing regex from the getAddress() should reduce usage a lot.

**Comment by andreasdc** [comment]
> > You mean with the latest 2 patches? I did optimizations to the initChannel method pretty similar, I reached around 0.5% improvement, the one with sanitizing address I will test later as I don't want to risk it being broken atm.
> 
> Tested and seems not broken. Removing regex from the getAddress() should reduce usage a lot.

Seperate handlers for each player are not needed?
