### ISSUE TITLE
There is a problem connecting to the server.

### ISSUE THREAD

**Issue by geumu** [2lstudios-mc/FlameCord#22]
The following error log appears on Bungeecord and I cannot connect to the server.

[19:04:29 INFO]: [geumu] disconnected with: IllegalReferenceCountException : refCnt: 0, decrement: 1 @ io.netty.util.internal.ReferenceCountUpdater:74

**Comment by linsaftw** [comment]
Hi, please try this release => https://github.com/2lstudios-mc/FlameCord/releases/tag/9f67dca

Reopen if it still happens :)

**Comment by geumu** [comment]
hi this error eccur

[05:06:55 INFO]: 127.0.0.1 had been firewalled from the proxy!
[05:06:55 INFO]: [Manager] disconnected with: IllegalReferenceCountException : refCnt: 0, decrement: 1 @ io.netty.util.internal.ReferenceCountUpdater:74
[05:06:59 INFO] [RewardProProxy]: Update playTime for player with uuid 5a055e40-676b-4d73-bf76-56ef33e7dcf9

**Comment by linsaftw** [comment]
I will keep trying to find a fix. Thanks.

**Comment by linsaftw** [comment]
Hi, please take a look at the latest release. :)

**Comment by gstio86** [comment]
I just tested the 1.5.0 version and this error appears again
1.4.9 version is working 
![image](https://user-images.githubusercontent.com/74390539/116801252-9fa86c00-ab3a-11eb-815b-bb816fd521a3.png)

**Comment by linsaftw** [comment]
> I just tested the 1.5.0 version and this error appears again
> 1.4.9 version is working
> ![image](https://user-images.githubusercontent.com/74390539/116801252-9fa86c00-ab3a-11eb-815b-bb816fd521a3.png)

What happens if you test in a empty bungee server? I don't have the same issues. What version are you running?

**Comment by gstio86** [comment]
@linsaftw 
I just use empty bungeecord , version is 0.5.0
My backend server is mohist, this error appears when connecting

**Comment by linsaftw** [comment]
> @linsaftw
> I just use empty bungeecord , version is 0.5.0
> My backend server is mohist, this error appears when connecting

I mean what version is your spigot server? Can you lend me a list of plugins so i can recreate the error?

**Comment by gstio86** [comment]
I use [mohist ](https://mohistmc.com/download/) 1.12.2 version
No plugins installed

**Comment by linsaftw** [comment]
> I use [mohist ](https://mohistmc.com/download/) 1.12.2 version
> No plugins installed

No plugins on the spigot server? And what plugins on bungee?

**Comment by gstio86** [comment]
Neither is installed, I use a clean server test

**Comment by linsaftw** [comment]
> Neither is installed, I use a clean server test

Alright! I will investigate the issue and try to fix it :) It is probably due to the new bytebuf release update.

**Comment by gstio86** [comment]
![image](https://user-images.githubusercontent.com/74390539/118898001-25e7ef00-b93e-11eb-9773-523870ee875b.png)
I am using version 0.5.1 and this problem still occurs :(

**Comment by linsaftw** [comment]
> ![image](https://user-images.githubusercontent.com/74390539/118898001-25e7ef00-b93e-11eb-9773-523870ee875b.png)
> I am using version 0.5.1 and this problem still occurs :(

Yes, we still don't know what could be causing it, probably the release of the latest updates, i will now test 1.12 spigot with FlameCord to see if this error exists.

**Comment by linsaftw** [comment]
Hi, i've replicated the issue. It only happens when joining a Modded Server with a Modded Client.

Here is the stacktrace -> https://pastebin.com/M79VNAyN

I will try to fix Forge support soon :)

**Comment by linsaftw** [comment]
Hi, we fixed forge support! We are soon releasing the new version :)
