### ISSUE TITLE
Question regarding flamecord

### ISSUE THREAD

**Issue by Blocksnmore** [2lstudios-mc/FlameCord#25]
Is there a reason that flamecord is seperate from travertine and doesn't PR the code into travertine?

**Comment by linsaftw** [comment]
> Is there a reason that flamecord is seperate from travertine and doesn't PR the code into travertine?

My code is not as high quality as Travertine's. It is more like an "urgent" patch until someone makes a better version of it.

It would be nice to see BungeeCord or Waterfall add deeper security measures and configuration values :)
