### ISSUE TITLE
List module formatting

### ISSUE THREAD

**Issue by AfkF24** [2lstudios-mc/FlameCord#3]
Hello, so I remembered there were ways to format the `/glist` command output in a previous FlameCord version which (probably) got removed during the recode. Any plans to bring this back? Was quite useful!

Regards

**Comment by MacacoLew** [comment]
messages.yml

command_list: '&a[{0}] &e({1}): &r{2}'

**Comment by AfkF24** [comment]
> messages.yml
> 
> command_list: '&a[{0}] &e({1}): &r{2}'

I am aware of that, however there used to be an option where you could format the whole output of the /glist command, and not just the server list line.

**Comment by LinsaFTW** [comment]
Hi, how would the format look after the changes are implemented? How do you want the config to look? something like "command_list_format: "&aServers:\n&r{0}" ?

**Comment by AfkF24** [comment]
> Hi, how would the format look after the changes are implemented? How do you want the config to look? something like "command_list_format: '&aServers:\n&r{0}'" ?

Exactly this.

**Comment by LinsaFTW** [comment]
Ok thanks :) I will think about this. Seems like a nice idea.

**Comment by linsaftw** [comment]
Done on 2af084a
