### ISSUE TITLE
I'm having a problem with FlameCord

### ISSUE THREAD

**Issue by sergservis** [2lstudios-mc/FlameCord#37]
I'm having a problem with FlameCord. I have the MoveMeNow plugin installed which allows not to kick the player from the server if he was kicked out for a specific reason (the player moves to the lobby) The problem is that FlameCord disconnects the player from the server differently and this causes errors. Question: how does FlameCord disconnect the player from the server? What is the reason?
https://www.spigotmc.org/resources/movemenow.17/?__cf_chl_jschl_tk__=2640b32d92cb16e4bdd3fa4cc87a4b227acf56d4-1622186493-0-AexjEcEoY98UhhmwEY0ldX8IhX1aJuobDL6IZek2vi2ix4Y56eRyq-S6dD3DYV_erjxFjBPsiBxK9cT5Aa0aulCdXeMLjcrbvpEE5TlMbWbPFKRZ8D-UGjB5gocTNrLMDF9X9PpaLZGpAU6IE8aQZ4DNXG6gi47SKUFdRekCuetCQ-usZvVCyX4WvPobyWqVqAd5z1Cipeq8ZCxfAY7VwOMPreh94E3eEfd9xTTvZxEpLGTW32lVzkP5ua1ve4OC291fqwcc74-eY3mFoA0CGsaatcrSpNC2wBVDaKjHlJCJiILlo-Sjxh1cDMlTg9Ub-Q_qZaB2HrzwbKNEEvk1F_WivSeQOqt6lpLNPwYE9LZmnZ2Cfbv6wF_7_NF5QCzdYRPUklvBCymKU-EQqJEJQuG9a85Iy4LPvLYkKF2nfZ2r

**Comment by 4drian3d** [comment]
You should avoid using outdated plugins, the plugin you mention has not been updated for 6 years, its last update in SpigotMC is a reupload of the 2015 version without any change or compatibility fix even with current Bungeecord.

**Comment by sergservis** [comment]
> You should avoid using outdated plugins, the plugin you mention has not been updated for 6 years, its last update in SpigotMC is a reupload of the 2015 version without any change or compatibility fix even with current Bungeecord.

non-standard Bungeecord plugin still works without issue

**Comment by linsaftw** [comment]
This cant be fixed at the moment as we had to do this to have safe disconnections on FlameCord and this prevents crashing during bot attacks.
