### ISSUE TITLE
Problem with ban message

### ISSUE THREAD

**Issue by xGlenor** [2lstudios-mc/FlameCord#38]
Can the characters be increased? I have a problem that a banned player, instead of receiving a banning message, receives the following message: 

`[13:54:11 INFO]: [Glenor] disconnected with: Exception Connecting:DecoderException : net.md_5.bungee.protocol.OverflowPacketException: Cannot receive string longer than 1024 (got 1142 characters) @ io.netty.handler.codec.MessageToMessageDecoder:98`

**Comment by linsaftw** [comment]
> Can the characters be increased? I have a problem that a banned player, instead of receiving a banning message, receives the following message:
> 
> `[13:54:11 INFO]: [Glenor] disconnected with: Exception Connecting:DecoderException : net.md_5.bungee.protocol.OverflowPacketException: Cannot receive string longer than 1024 (got 1142 characters) @ io.netty.handler.codec.MessageToMessageDecoder:98`

Hi, please don't send messages too big :) 1024 characters is a lot for a simple message and this can be abused by bots/players to consume bandwidth.
