### ISSUE TITLE
Tab suggestions modifier

### ISSUE THREAD

**Issue by AfkF24** [2lstudios-mc/FlameCord#4]
Hello, basically having a config option to whitelist (or blacklist) Bungee commands which should be displayed on tab suggestions could be a feature unique to FlameCord - as this is something not possible on classic BungeeCord. I might be wrong here, but apparently Waterfall has a way to modify tab suggestion outputs which is ideally something FlameCord should have its hands on too. Bungee plugins usually tend not to register permissions the way they're supposed to, so every single command gets displayed on tab suggestions, which is rather annoying.

I am aware that there's `throttling.tab_complete: -1` in `waterfall.yml`, but this doesn't really feel like the way to go.

Regards

**Comment by LinsaFTW** [comment]
Hi, what exactly do you mean with this? Can you show me an example configuration?

**Comment by AfkF24** [comment]
A plugin adapting Waterfall's ability to modify this has actually just came out recently, https://www.spigotmc.org/resources/%E2%AD%90-suggestion-blocker-hide-command-suggestions-%E2%AD%90-tab-complete-blocker-1-13-1-16.72191/. This can be closed really due to this.

**Comment by LinsaFTW** [comment]
Ok i will see what i can do :) Maybe ill make a plugin, this doesn't seem like something to make in a fork. I will think about it.
