### ISSUE TITLE
Licensing violations in FlameCord related to code from Velocity

### ISSUE THREAD

**Issue by astei** [2lstudios-mc/FlameCord#43]
The FlameCord includes [a patch](https://github.com/2lstudios-mc/FlameCord/blob/c3e6a00b47d93cb3b47e209223043eceeee41198/Waterfall-Proxy-Patches/0010-Use-Velocity-Frame-Decoder.patch) including code from my project [Velocity](https://velocitypowered.com), specifically a renamed version of [`MinecraftVarintFrameDecoder.java`](https://github.com/VelocityPowered/Velocity/blob/dev/1.1.0/proxy/src/main/java/com/velocitypowered/proxy/protocol/netty/MinecraftVarintFrameDecoder.java). This code is licensed under the GPLv3 license and FlameCord is in flagrant violation of it. Specifically:

* The GPLv3 is "viral" - including GPL code in a project automatically makes it a derived work of the GPLed project. FlameCord is still MIT licensed.
* You must disclose the changes you made to this file (in this case, renaming the file to the equivalent BungeeCord class).
* Include the original copyright disclaimer from the Velocity project
* Attribution that I made the changes.
* Include the original source of the material (for my purposes, a link in the README and on your website to https://velocitypowered.com as appropriate would be sufficient).

## How to rectify the issue

There's two main options:

* Remove the patch entirely.
* Relicense your project under GPLv3 and modify the author to be me (`Andrew Steinborn <git@steinborn.me>`) and rectify the issues mentioned above.

**Comment by linsaftw** [comment]
Hello, I will issue a replacement of the patch by a self implementation of a simple frame decoder to fix this issue.

**Comment by linsaftw** [comment]
Fixed on e8bc14b

**Comment by B4RC0DE-TM** [comment]
Fixed Thanks for bothering!
