### ISSUE TITLE
Esto no es un bug pero es una pregunta.

### ISSUE THREAD

**Issue by craciu25yt** [2lstudios-mc/FlameCord#47]
Hola 2LS Studios y Developers de ArkFlame. Queria preguntar por qué Flamecord es vendido en MC Market, pero aquí lo reglan? Además 2LS ExpoitFixer esta gratis en spigot pero en MC Market no?

**Comment by linsaftw** [comment]
De esta forma se combate la pirateria y me quedo con el credito de la misma.

El que quiera comprar puede comprar, el que quiera descargar gratis puede descargar gratis.

Ahora bien, si el mismo quiere notificationes en la web de mc-market cada vez que sale update tendra que comprarlo.
