### ISSUE TITLE
High Cpu Usage

### ISSUE THREAD

**Issue by aril3721** [2lstudios-mc/FlameCord#49]
Hello. I Used Flamecord Version 0.5.9 (Latest/Free Version) I Dont Know Why My Bungeecord Using 40% - 200% Cpu Usage. Like Cpu Usage Spike. From 40 To 200 And 200 To 40 - 20 It Make Me  Confused. Before I use Flamecord 0.5.8 Its Normal. pls help me.

My Normal Amount Player
20 - 50 Player Per Day

This Is My Bungee List Plugin
![image](https://user-images.githubusercontent.com/67541360/125018619-0c466680-e0a8-11eb-9914-69411b65ba09.png)

Spesification
3GB Ram
2 Core Cpu

**Comment by linsaftw** [comment]
Hi, I can't reproduce high CPU usage in my end.

![image](https://user-images.githubusercontent.com/25271111/125028011-a7feb500-e05d-11eb-91b2-80b6915e9e7f.png)

This seems to be an issue from plugins and not FlameCord.

To diagnose this try the following:

1. Remove plugins until CPU usage is fixed.
2. Use a profiler to see detailed CPU usage of the instance and see which stuff is using up CPU.
