### ISSUE TITLE
1.17.1 release when?

### ISSUE THREAD

**Issue by Tyloon1e** [2lstudios-mc/FlameCord#51]
Much love

**Comment by linsaftw** [comment]
GitHub version is already 1.17.1. To release on MCM I need to test it before.

**Comment by 4drian3d** [comment]
> 1.17.1 release when?

You can download FlameCord 1.17.1 from https://github.com/2lstudios-mc/FlameCord/actions/runs/1005730942 but the official release with testing is not yet available.
