### ISSUE TITLE
Flamecord +antibot Crash

### ISSUE THREAD

**Issue by LucidAPs** [2lstudios-mc/FlameCord#52]
These are the logs
https://nekobin.com/sunimisoka

It just keeps happening, what am I supposed to do?
I am using
FlameCord - Update 0.6.0 and your antibot
I was using 6gb for ram for bungee.

**Comment by linsaftw** [comment]
Hello, this is not an issue from FlameCord/AntiBot. As you can see in the log this is caused because of a plugin consuming high CPU usage on events. Please try removing plugins until fixed.
