### ISSUE TITLE
Travertine and questions

### ISSUE THREAD

**Issue by andreasdc** [2lstudios-mc/FlameCord#58]
Does FlameCord contains Travertine's patch? Does it have better performance than Waterfall? Is it stable and safe?

**Comment by linsaftw** [comment]
Yes

**Comment by andreasdc** [comment]
> Yes, it is a fork.

So it supports 1.7?

**Comment by linsaftw** [comment]
> > Yes, it is a fork.
> 
> So it supports 1.7?

Oh sorry, some months ago we unforked from travertine and we are Waterfall now. If you want 1.7 support you need ViaRewind, ViaVersion and ViaBackwards installed in BungeeCord.

**Comment by andreasdc** [comment]
> > > Yes, it is a fork.
> > 
> > 
> > So it supports 1.7?
> 
> Oh sorry, some months ago we unforked from travertine and we are Waterfall now. If you want 1.7 support you need ViaRewind, ViaVersion and ViaBackwards installed in BungeeCord.

Can you add travertine's patch or make it configurable? :)

**Comment by linsaftw** [comment]
> > > > Yes, it is a fork.
> > > 
> > > 
> > > So it supports 1.7?
> > 
> > 
> > Oh sorry, some months ago we unforked from travertine and we are Waterfall now. If you want 1.7 support you need ViaRewind, ViaVersion and ViaBackwards installed in BungeeCord.
> 
> Can you add travertine's patch or make it configurable? :)

No because it was abandoned. ViaRewind instead keeps updating for better 1.7 support :)

**Comment by andreasdc** [comment]
@linsaftw ViaVersion doesn't recommend keeping VV plugins on bukkit and bungee.

**Comment by linsaftw** [comment]
> @linsaftw ViaVersion doesn't recommend keeping VV plugins on bukkit and bungee.

Just use it on bungee :)

**Comment by andreasdc** [comment]
> > @linsaftw ViaVersion doesn't recommend keeping VV plugins on bukkit and bungee.
> 
> Just use it on bungee :) no need to run on both.

When using on bukkit it has more featuers

**Comment by linsaftw** [comment]
> > > @linsaftw ViaVersion doesn't recommend keeping VV plugins on bukkit and bungee.
> > 
> > 
> > Just use it on bungee :) no need to run on both.
> 
> When using on bukkit it has more featuers

Which ones? If I remember it just had a few bugs on bungee.

**Comment by andreasdc** [comment]
> > > > @linsaftw ViaVersion doesn't recommend keeping VV plugins on bukkit and bungee.
> > > 
> > > 
> > > Just use it on bungee :) no need to run on both.
> > 
> > 
> > When using on bukkit it has more featuers
> 
> Which ones? If I remember it just had a few bugs on bungee.

Probably block connections, maybe more I'm not sure.

**Comment by linsaftw** [comment]
> > > > > @linsaftw ViaVersion doesn't recommend keeping VV plugins on bukkit and bungee.
> > > > 
> > > > 
> > > > Just use it on bungee :) no need to run on both.
> > > 
> > > 
> > > When using on bukkit it has more featuers
> > 
> > 
> > Which ones? If I remember it just had a few bugs on bungee.
> 
> Probably block connections, maybe more I'm not sure.

Alrighty but again the Travertine solution is worse then having it on Bungee & Bukkit at the same time.

**Comment by andreasdc** [comment]
Why is it worse?

**Comment by linsaftw** [comment]
> Why is it worse?

There is a reason it was discontinued right? It had many bugs and was hard to maintain.

**Comment by andreasdc** [comment]
> > Why is it worse?
> 
> There is a reason it was discontinued right? It had many bugs and was hard to maintain.

What was hard to maintain with keeping 1 or 2 patches? I didn't had bugs with it

**Comment by linsaftw** [comment]
> > > Why is it worse?
> > 
> > 
> > There is a reason it was discontinued right? It had many bugs and was hard to maintain.
> 
> What was hard to maintain with keeping 1 or 2 patches? I didn't had bugs with it

I just don't know how packet mapping works, and I don't know how to maintain it either so the best option was to let this to the hands of ViaRewind. If you want new features for ViaRewind ask the developers for them. They already make connections work on Bungee for 1.17 so it's possible for other versions.

**Comment by andreasdc** [comment]
> > > > Why is it worse?
> > > 
> > > 
> > > There is a reason it was discontinued right? It had many bugs and was hard to maintain.
> > 
> > 
> > What was hard to maintain with keeping 1 or 2 patches? I didn't had bugs with it
> 
> I just don't know how packet mapping works, and I don't know how to maintain it either so the best option was to let this to the hands of ViaRewind. If you want new features for ViaRewind ask the developers for them. They already make connections work on Bungee for 1.17 so it's possible for other versions.

Block connections?

**Comment by linsaftw** [comment]
> > > > > Why is it worse?
> > > > 
> > > > 
> > > > There is a reason it was discontinued right? It had many bugs and was hard to maintain.
> > > 
> > > 
> > > What was hard to maintain with keeping 1 or 2 patches? I didn't had bugs with it
> > 
> > 
> > I just don't know how packet mapping works, and I don't know how to maintain it either so the best option was to let this to the hands of ViaRewind. If you want new features for ViaRewind ask the developers for them. They already make connections work on Bungee for 1.17 so it's possible for other versions.
> 
> Block connections?

Yeah, connecting walls etc works on bungee version of viaversion for 1.8 -> 1.16 so it is possible to do the same inverse.
