### ISSUE TITLE
Cannot get ID for packet class with TAB

### ISSUE THREAD

**Issue by samcarsonx** [2lstudios-mc/FlameCord#60]
I was originally going to use TAB on each server within the network, but when I added a second server I noticed that I was having the same issue as #59 so a helper in the TAB support Discord suggested that I install it on the proxy instead. That's when I discovered this:

When using the TAB plugin (latest version v2.9.2) on FlameCord v0.6.2, this error kicks players off when they attempt to connect:
`[15:52:00 INFO]: [samcarsonx] disconnected with: EncoderException : java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.ScoreboardObjective in phase GAME with direction TO_CLIENT @ io.netty.handler.codec.MessageToByteEncoder:125`
There is no stack trace other than this. I found [this](https://github.com/SpigotMC/BungeeCord/blob/master/protocol/src/main/java/net/md_5/bungee/protocol/Protocol.java#L576) which is what seems to throw the error, if that helps.

I spoke to the developer of the plugin and tested it with Waterfall instead (which works) and therefore came to the conclusion that it is an error within FlameCord.

**Comment by linsaftw** [comment]
That's not mine at all. That's from BungeeCord. Maybe I need to update to latest Waterfall version to fix this issue. I will close this for now as it is an issue from BungeeCord itself and I basically probably have to update.

**Comment by andreasdc** [comment]
> That's not mine at all. That's from BungeeCord. Maybe I need to update to latest Waterfall version to fix this issue. I will close this for now as it is an issue from BungeeCord itself and I basically probably have to update.

FlameCord is on bungee from 1 month ago? Fix that please 💀

**Comment by linsaftw** [comment]
> > That's not mine at all. That's from BungeeCord. Maybe I need to update to latest Waterfall version to fix this issue. I will close this for now as it is an issue from BungeeCord itself and I basically probably have to update.
> 
> FlameCord is on bungee from 1 month ago? Fix that please 💀

Sure, next time I am free I will do that.
