### ISSUE TITLE
Firewall-Names not working

### ISSUE THREAD

**Issue by Luccboy** [2lstudios-mc/FlameCord#62]
Hi, you can add names in flamecord.yml:
![image](https://user-images.githubusercontent.com/58391278/131266245-97e1df15-6084-4f33-a2d2-acf8b7f59adf.png)
But the problem is that this feature is not working and not implemented properly in the code. So players/bots with a name that is included in the list are not firewalled. Would be great if this function could be added/fixed :)

**Comment by linsaftw** [comment]
![image](https://user-images.githubusercontent.com/25271111/131270320-9de680a0-6ec3-4bd2-aff7-4daf5a7712ce.png)

Please confirm that it isnt working. It is integrated in the isFirewalled() method.

**Comment by Luccboy** [comment]
Maybe i missed something, but the `isFirewalled(String name)` method is nowhere executed.

**Comment by andreasdc** [comment]
Probably here
https://github.com/2lstudios-mc/FlameCord/blob/498bbbbdecdac46b692675d018e2f16c9f5d11ed/Waterfall-Proxy-Patches/0024-Firewall-System.patch#L386

**Comment by Luccboy** [comment]
> Probably here
> https://github.com/2lstudios-mc/FlameCord/blob/498bbbbdecdac46b692675d018e2f16c9f5d11ed/Waterfall-Proxy-Patches/0024-Firewall-System.patch#L386
> 
> 
> but with address, with name I don't see anything

But in this case, the method is checking if the IP-address is firewalled and not if the username is firewalled, or am I wrong?

**Comment by Luccboy** [comment]
IntelliJ also says that the method is not used 🤔
![image](https://user-images.githubusercontent.com/58391278/131270999-fd8f89a3-7349-4c72-95dc-8b4a79b92bd3.png)

**Comment by linsaftw** [comment]
Oh sorry, thank you. I will see what I can do.

**Comment by Luccboy** [comment]
Maybe I can open a PR: So if a player joins with a username on this list, his address should be firewalled, am I right?
