### ISSUE TITLE
Error on version 1.8.8

### ISSUE THREAD

**Issue by MoloBoso** [2lstudios-mc/FlameCord#64]
Hello,  i have FlameCord(Proxy) and spigot version 1.8.8(Lobby) , and i can't connect to Lobby. I have only this error: 

"readAddress(..) failed: Connection reset by peer"

**Comment by LewUwU** [comment]
Not helpful, can you try with default Waterfall?

**Comment by MoloBoso** [comment]
Nothing change just same error

**Comment by linsaftw** [comment]
> Nothing change just same error

Its a Waterfall issue then, not mine.
