### ISSUE TITLE
Motd System configured with FlameCord has no effect

### ISSUE THREAD

**Issue by DJelly4K** [2lstudios-mc/FlameCord#65]
I enabled custom-motd in flamecord.yml
and do nothing in config.yml
but it still shows the first downstream server motd
can this problem fix? thanks

**Comment by linsaftw** [comment]
> I enabled custom-motd in flamecord.yml and do nothing in config.yml but it still shows the first downstream server motd can this problem fix? thanks

Disable force_default_server and make sure u don't have any other motd plugins installed.
