### ISSUE TITLE
Feature Requests regarding the new MOTD system in 0.6.4

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [2lstudios-mc/FlameCord#68]
Due to the new motd changes in Flamecord and the therefore happening change from cleanmotd to it for security and performance reasons, it would be cool if you could add the following over time, if possible/safe:

• Hex support.
• To point above add Gradient support.
• Center message support.
• Protocol version (if still existent in 1.17.1, which I do not think, atleast it did not show up on my 1.17.1 vanilla client anymore, on 1.16.5 it did, with clean motd)
• Protocol hover - display nice infos like socials or other useful informations in the protocol hover event.
• JustOneMore - self explantory, one more player slot being free displayed than online players.
I know it won't be added very soon, since we talked about it, just wanted to post it here to have an up to date reminder!:)

Best regards.

**Comment by xIsm4** [comment]
> event

I mean, u can use any plugin of MotD to do that? I think just FlameCord searchs a basic Lightweight motd

**Comment by linsaftw** [comment]
> > event
> 
> I mean, u can use any plugin of MotD to do that? I think just FlameCord searchs a basic Lightweight motd

Using plugins for motd makes you vulnerable to attacks as reflection is heavy.

**Comment by linsaftw** [comment]
Any API for getting hex support with gradients on BungeeCord? Iridium is only for Spigot.

**Comment by linsaftw** [comment]
Until there is a good method for HEX we will close this issue.
