### ISSUE TITLE
Option to Disable 1.7.x Support

### ISSUE THREAD

**Issue by nicholasveronico** [2lstudios-mc/FlameCord#69]
An option in flamecord.yml to disable 1.7 support so players aren’t tricked into thinking they can log onto the server with 1.7, then being kicked.

**Comment by xIsm4** [comment]
> An option in flamecord.yml to disable 1.7 support so players aren’t tricked into thinking they can log onto the server with 1.7, then being kicked.

Well, actually that's really dumb using FlameCord i mean 1.7x u just can do this:

```java
  @EventHandler(priority = (byte) 256)
  public void onLogin(LoginEvent evt) {
    if (!evt.isCancelled()) {
    //Cancells the join on 1.7.10x (U can switch the protocol)
      if (evt.getConnection().getVersion() != 5) {
        evt.setCancelled(true);
        evt.setCancelReason(fromLegacyText("§cSorry, but u can't join our Network with that version!"));
        return;
      }
```

**Comment by nicholasveronico** [comment]
> > An option in flamecord.yml to disable 1.7 support so players aren’t tricked into thinking they can log onto the server with 1.7, then being kicked.
> 
> Well, actually that's really dumb using FlameCord i mean 1.7x u just can do this:
> 
> ```java
>   @EventHandler(priority = (byte) 256)
>   public void onLogin(LoginEvent evt) {
>     if (!evt.isCancelled()) {
>     //Cancells the join on 1.7.10x (U can switch the protocol)
>       if (evt.getConnection().getVersion() != 5) {
>         evt.setCancelled(true);
>         evt.setCancelReason(fromLegacyText("§cSorry, but u can't join our Network with that version!"));
>         return;
>       }
> ```

Since I don’t use ViaBackwards on my hubs, the join is already cancelled. The thing is, the player doesn’t see the outdated version ping message on the 1.7.x server list and they think there’s 1.7 support even though it’s stated in the motd “1.8-1.17”. What I meant by having an option to disable 1.7.x support was to make the ping message “Flamecord 1.8.x - 1.17.x” and indicate that it is the incorrect version on 1.7 clients.

**Comment by xIsm4** [comment]
> > > An option in flamecord.yml to disable 1.7 support so players aren’t tricked into thinking they can log onto the server with 1.7, then being kicked.
> > 
> > 
> > Well, actually that's really dumb using FlameCord i mean 1.7x u just can do this:
> > ```java
> >   @EventHandler(priority = (byte) 256)
> >   public void onLogin(LoginEvent evt) {
> >     if (!evt.isCancelled()) {
> >     //Cancells the join on 1.7.10x (U can switch the protocol)
> >       if (evt.getConnection().getVersion() != 5) {
> >         evt.setCancelled(true);
> >         evt.setCancelReason(fromLegacyText("§cSorry, but u can't join our Network with that version!"));
> >         return;
> >       }
> > ```
> 
> Since I don’t use ViaBackwards on my hubs, the join is already cancelled. The thing is, the player doesn’t see the outdated version ping message on the 1.7.x server list and they think there’s 1.7 support even though it’s stated in the motd “1.8-1.17”. What I meant by having an option to disable 1.7.x support was to make the ping message “Flamecord 1.8.x - 1.17.x” and indicate that it is the incorrect version on 1.7 clients.

U can change the version like some Proxy forks implementation, changing this:

public class Messages {
  public static String proxyName = "FlameCord %versions%";
  
  public static String versions = "(1.8.x - 1.17x)";

}

    @Override
    public String getName()
    {
        return "FlameCord";
    }

    @Override
    public String getVersion()
    {
           return Messages.proxyName.replaceAll(Messages.version)
      .replaceAll("%versions%", Messages.versions);
    }

**Comment by linsaftw** [comment]
> > > > An option in flamecord.yml to disable 1.7 support so players aren’t tricked into thinking they can log onto the server with 1.7, then being kicked.
> > > 
> > > 
> > > Well, actually that's really dumb using FlameCord i mean 1.7x u just can do this:
> > > ```java
> > >   @EventHandler(priority = (byte) 256)
> > >   public void onLogin(LoginEvent evt) {
> > >     if (!evt.isCancelled()) {
> > >     //Cancells the join on 1.7.10x (U can switch the protocol)
> > >       if (evt.getConnection().getVersion() != 5) {
> > >         evt.setCancelled(true);
> > >         evt.setCancelReason(fromLegacyText("§cSorry, but u can't join our Network with that version!"));
> > >         return;
> > >       }
> > > ```
> > 
> > 
> > Since I don’t use ViaBackwards on my hubs, the join is already cancelled. The thing is, the player doesn’t see the outdated version ping message on the 1.7.x server list and they think there’s 1.7 support even though it’s stated in the motd “1.8-1.17”. What I meant by having an option to disable 1.7.x support was to make the ping message “Flamecord 1.8.x - 1.17.x” and indicate that it is the incorrect version on 1.7 clients.
> 
> That's just the brand name, u can edit it so easy, or even do it a config file Lol, u don't even need viabackwards. Even if u want something like a task, or a boolean "true/false" u can do it on the WaterfallConfiguration, following how they do it. But if u say that it's already cancelled by ViaBackwards, then just switch the version i guess?
> 
> ```java
> public class Messages {
>  public static String proxyName = "FlameCord %versions%";
>  
>  public static String versions = "(1.8.x - 1.17x)";
> }
> 
>    @Override
>    public String getName()
>    {
>        return "FlameCord";
>    }
> 
>    @Override
>    public String getVersion()
>    {
>           return Messages.proxyName.replaceAll(Messages.version)
>      .replaceAll("%versions%", Messages.versions);
>    }
>     ```
> ```

Brand name doesn't appear bc FlameCord shows 1.7 as supported.

**Comment by xIsm4** [comment]
> > > > > An option in flamecord.yml to disable 1.7 support so players aren’t tricked into thinking they can log onto the server with 1.7, then being kicked.
> > > > 
> > > > 
> > > > Well, actually that's really dumb using FlameCord i mean 1.7x u just can do this:
> > > > ```java
> > > >   @EventHandler(priority = (byte) 256)
> > > >   public void onLogin(LoginEvent evt) {
> > > >     if (!evt.isCancelled()) {
> > > >     //Cancells the join on 1.7.10x (U can switch the protocol)
> > > >       if (evt.getConnection().getVersion() != 5) {
> > > >         evt.setCancelled(true);
> > > >         evt.setCancelReason(fromLegacyText("§cSorry, but u can't join our Network with that version!"));
> > > >         return;
> > > >       }
> > > > ```
> > > 
> > > 
> > > Since I don’t use ViaBackwards on my hubs, the join is already cancelled. The thing is, the player doesn’t see the outdated version ping message on the 1.7.x server list and they think there’s 1.7 support even though it’s stated in the motd “1.8-1.17”. What I meant by having an option to disable 1.7.x support was to make the ping message “Flamecord 1.8.x - 1.17.x” and indicate that it is the incorrect version on 1.7 clients.
> > 
> > 
> > That's just the brand name, u can edit it so easy, or even do it a config file Lol, u don't even need viabackwards. Even if u want something like a task, or a boolean "true/false" u can do it on the WaterfallConfiguration, following how they do it. But if u say that it's already cancelled by ViaBackwards, then just switch the version i guess?
> > ```java
> > public class Messages {
> >  public static String proxyName = "FlameCord %versions%";
> >  
> >  public static String versions = "(1.8.x - 1.17x)";
> > }
> > 
> >    @Override
> >    public String getName()
> >    {
> >        return "FlameCord";
> >    }
> > 
> >    @Override
> >    public String getVersion()
> >    {
> >           return Messages.proxyName.replaceAll(Messages.version)
> >      .replaceAll("%versions%", Messages.versions);
> >    }
> >     ```
> > ```
> 
> Brand name doesn't appear bc FlameCord shows 1.7 as supported.

He want to edit the name too.

**Comment by linsaftw** [comment]
Configuration won't be added to disable 1.7 support.
