### ISSUE TITLE
Support aarch64 device

### ISSUE THREAD

**Issue by DJelly4K** [2lstudios-mc/FlameCord#73]
If I use FlameCord in aarch64 linux:
(Ubuntu 20.04 aarch64)
![image](https://user-images.githubusercontent.com/68630033/140971658-5a79f19a-7287-462d-af58-f915222bd1d2.png)
Epoll is not working, falling back to NIO: UnsatisfiedLinkError : could not load a native library: netty_transport_native_epoll_aarch_64 @ io.netty.util.internal.NativeLibraryLoader:221

Although it is not a serious problem, I hope it can be resolved, thanks

**Comment by linsaftw** [comment]
This issue is from BungeeCord/Waterfall and has to be solved there instead.
