### ISSUE TITLE
Option to allow invalid characters

### ISSUE THREAD

**Issue by mocha666** [2lstudios-mc/FlameCord#77]
For some special reasons, my server uses a third-party account service. When I use this server, a login prohibition prompt of "username contains invalid characters" will appear. It is recommended to modify this detection to regular expression

**Comment by linsaftw** [comment]
I don't think it is a good idea to allow invalid characters.

**Comment by mocha666** [comment]
OK, this is just a functional suggestion, because I am a server administrator from China Our community will use some invalid characters For example, Chinese characters

**Comment by mocha666** [comment]
![00348550](https://user-images.githubusercontent.com/35604975/146723218-18935411-e7e7-4b2a-828e-b678419c198a.png)

**Comment by linsaftw** [comment]
I understand. It seems like a good idea for non-latin servers.

**Comment by mocha666** [comment]
等你更新啦, 嘻嘻
When you update, hee hee

**Comment by linsaftw** [comment]
> 等你更新啦, 嘻嘻 When you update, hee hee

When i have free time :) I am doing paid jobs at the moment because of economic issues.

**Comment by xIsm4** [comment]
> OK, this is just a functional suggestion, because I am a server administrator from China Our community will use some invalid characters For example, Chinese characters

I thing that's not good can, because weill break the invalid name check of BungeeCord.
Then they can trow bots with that type of name and fuck the server.
Also Minecraft even doesn't allow it.

**Comment by LewUwU** [comment]
> > OK, this is just a functional suggestion, because I am a server administrator from China Our community will use some invalid characters For example, Chinese characters
> 
> I thing that's not good can, because weill break the invalid name check of BungeeCord. Then they can trow bots with that type of name and fuck the server. Also Minecraft even doesn't allow it.

Minecraft protocol allows that

**Comment by linsaftw** [comment]
Done on b0a1abdf310d3adcd29d7a4fa8538a4330030c8a

**Comment by mocha666** [comment]
think you, netease version of minecraft allows this characters.
