### ISSUE TITLE
Enquiries on FlameCord's custom motd system

### ISSUE THREAD

**Issue by mokdennie26** [2lstudios-mc/FlameCord#78]
For some reason, when my config.yml has the following settings applied, the flamecord's custom motd system will not override.

`priorities: (is set)`
`force_default_server: true`

It will only display the MOTD of the prioritised default server.
I guess it's not an issue with flamecord because it has always been like that for vanilla bungeecord.
It will read the default server's motd instead of the bungee's motd.

Uhmm just wondering if there's a way to use flamecord's custom motd system while having a forced default server?
You know, it has to be set like that to force people to login, and to provide a better security.

**Comment by linsaftw** [comment]
`force_default_server: true` -> disable this feature

You only need to use the priorities option to "force" a default server.
