### ISSUE TITLE
Patch 0016 and netty synchronisation?!

### ISSUE THREAD

**Issue by Janmm14** [2lstudios-mc/FlameCord#81]
Netty has inbuilt synchronisation per connection, so the placr we change the state variable while still in the same thread should not be relevant.

Or did you observe different behaviour?

**Comment by andreasdc** [comment]
What?

**Comment by linsaftw** [comment]
I had different behaviour were people can stuck at a state and abuse this to send multiple packets for encryption request. There is no reason to do it late, i think that doing it early is safer.

**Comment by linsaftw** [comment]
Maybe we can do something like... "in progress" boolean to avoid this kind of stuff.
