### ISSUE TITLE
FlameCord MOTD not working in 1.18.1 clients

### ISSUE THREAD

**Issue by benfiratkaya** [2lstudios-mc/FlameCord#83]
I'm using flamecord motd system (without plugin). MOTD working well in 1.8 or something. But my motd not showing in 1.18.1 clients.

**Comment by xIsm4** [comment]
> m using flamecord motd system (without plugin). MOTD working well in 1.8 or something. But my motd not showing in 1.18.1 clients.

For now i recommend you use CleanMotd.

**Comment by linsaftw** [comment]
No response received.
