### ISSUE TITLE
maybe connection problems?

### ISSUE THREAD

**Issue by TheWylot** [2lstudios-mc/FlameCord#84]
i recently used flamecord, when a player wants to connect, my Auth server tps is High(+19) but its laggy and have a lot of delays.

**Comment by TheWylot** [comment]
players some times should cancel their connection and spam it
they game freeze on Connecting to Server Loading

also im using 2LS Antibot

**Comment by TheWylot** [comment]
where can i send them

**Comment by linsaftw** [comment]
> where can i send them

Make a pastebin and post it here.

**Comment by linsaftw** [comment]
No response received.
