### ISSUE TITLE
Message.yml bug

### ISSUE THREAD

**Issue by PanHaskins** [2lstudios-mc/FlameCord#85]
![image](https://user-images.githubusercontent.com/58113388/153282176-106f1aa3-9337-4730-ae4c-2ebc79f6fc4b.png)
It is not possible to turn off rough text in the given text. I also tried &r
![image](https://user-images.githubusercontent.com/58113388/153282232-d17b015a-c9ec-4fd5-b008-7d5a04a4a293.png)

**Comment by linsaftw** [comment]
No response received.
