### ISSUE TITLE
Connection Issue 

### ISSUE THREAD

**Issue by Square661** [2lstudios-mc/FlameCord#88]
When I try and join my server (The proxy which is running the latest flamecord version) i get this error. Nothing in console https://gyazo.com/1cfb49d31c84ba01617b844ddfa34689

Do you have any idea what this error means? Could not find anything on the internet...

**Comment by linsaftw** [comment]
Never seen the issue before. Can't replicate on my end either. Seems like a plugin. Try without any plugins installed.
