### ISSUE TITLE
AntiBot System

### ISSUE THREAD

**Issue by linsaftw** [2lstudios-mc/FlameCord#89]
- Reconnect (Asks the player to reconnect before being able to join)
- Whitelist (IPs that accomplish certain conditions are excempted from checks)
- Blacklist (IPs on this list are temporally/permanently blocked)
- FastJoin (Blocks very fast connections)
- FastPing (Blocks very fast ping requests)
- Falling (Check if player falls and receives fall damage [Limbo])
- Velocity (Check if player receives velocity on damage [Limbo])
- Captcha (Ask the player to write characters on chat [Limbo])
- WebCaptcha (Ask the player to complete a webcaptcha before joining)
- FastChat (Check if player chats too fast after join)
- Redis integration for Blacklist/Whitelist.
- Threshold system (Only activate checks on bot attack)
- Player limit per IP

**Comment by andreasdc** [comment]
I love it <3 Can't wait!
Big configuration to set where captcha will be, messages etc. and it will be awesome. 🥇

**Comment by LewUwU** [comment]
+1

**Comment by iChocoMC** [comment]
nice

**Comment by linsaftw** [comment]
Done on 3847290d6600ae3ba6c9b68c7ca539da7608f4a7 (play.arkflame.com)

**Comment by andreasdc** [comment]
> Done on [3847290](https://github.com/2lstudios-mc/FlameCord/commit/3847290d6600ae3ba6c9b68c7ca539da7608f4a7) (arkflame.com)

Velocity, Falling?

**Comment by linsaftw** [comment]
Falling, Velocity, Captcha, WebCaptcha, Redis and Threshold are secondary features that will be done in the future. (I yet don't have a proper idea on how to implement this)
