### ISSUE TITLE
IvanCord patches

### ISSUE THREAD

**Issue by andreasdc** [2lstudios-mc/FlameCord#90]
Hey, I saw that IvanCord may containt couple interesting patches, that maybe with some communication with both sides they could be added to FlameCord? I think it will be good step for FlameCord to be even better alternative for all proxies.

Patches: https://github.com/MrIvanPlays/IvanCord/tree/master/Waterfall-Proxy-Patches

**Comment by linsaftw** [comment]
Please specify the patches in different issues and check for Ivan's permission to use the patches.

**Comment by andreasdc** [comment]
> Please specify the patches in different issues and check for Ivan's permission to use the patches.

Ivan gave you the permission as long as you give credit to him, so I guess it's mentioning that he's the author.

I don't want to be responsible for selecting the patches, I don't know which are already in FlameCord.
He has 33 patches, I'm not sure if it will be good to create the issue for every one.
Example patches:
https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0024-Reduce-load-on-bungee-by-so-called-BungeeSmasher-s.patch
https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0030-EventBus-speed-improvements.patch
https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0032-More-DoS-mitigations.patch
https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0033-Ping-and-close-changes.patch
And there are many more

**Comment by xIsm4** [comment]
> > Please specify the patches in different issues and check for Ivan's permission to use the patches.
> 
> Ivan gave you the permission as long as you give credit to him, so I guess it's mentioning that he's the author.
> 
> I don't want to be responsible for selecting the patches, I don't know which are already in FlameCord. He has 33 patches, I'm not sure if it will be good to create the issue for every one. Example patches: https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0024-Reduce-load-on-bungee-by-so-called-BungeeSmasher-s.patch https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0030-EventBus-speed-improvements.patch https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0032-More-DoS-mitigations.patch https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0033-Ping-and-close-changes.patch And there are many more

Bruh, 032 & 033 it's by FlameCord

**Comment by andreasdc** [comment]
> > > Please specify the patches in different issues and check for Ivan's permission to use the patches.
> > 
> > 
> > Ivan gave you the permission as long as you give credit to him, so I guess it's mentioning that he's the author.
> > I don't want to be responsible for selecting the patches, I don't know which are already in FlameCord. He has 33 patches, I'm not sure if it will be good to create the issue for every one. Example patches: https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0024-Reduce-load-on-bungee-by-so-called-BungeeSmasher-s.patch https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0030-EventBus-speed-improvements.patch https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0032-More-DoS-mitigations.patch https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0033-Ping-and-close-changes.patch And there are many more
> 
> Bruh, 032 & 033 it's by FlameCord.

And? Stop spreading useless information, Ivan summarized you when you told he uses only FlameCord's patches.

**Comment by linsaftw** [comment]
This patches will be taken in count. I will focus on the AntiBot feature for the moment.

**Comment by andreasdc** [comment]
> This patches will be taken in count. Thanks. I will focus on the AntiBot feature for the moment.

It can be reopened I guess.

**Comment by linsaftw** [comment]
> > This patches will be taken in count. Thanks. I will focus on the AntiBot feature for the moment.
> 
> It can be reopened I guess.

They have to be opened in different issues.

**Comment by andreasdc** [comment]
> > > This patches will be taken in count. Thanks. I will focus on the AntiBot feature for the moment.
> > 
> > 
> > It can be reopened I guess.
> 
> They have to be opened in different issues.

Do you want 30 issues? I don't know which one to pick :D

**Comment by linsaftw** [comment]
> > > > This patches will be taken in count. Thanks. I will focus on the AntiBot feature for the moment.
> > > 
> > > 
> > > It can be reopened I guess.
> > 
> > 
> > They have to be opened in different issues.
> 
> Do you want 30 issues? I don't know which one to pick :D

Haha nope, this has to be selected by someone that knows about the patches.

**Comment by andreasdc** [comment]
> > > > > This patches will be taken in count. Thanks. I will focus on the AntiBot feature for the moment.
> > > > 
> > > > 
> > > > It can be reopened I guess.
> > > 
> > > 
> > > They have to be opened in different issues.
> > 
> > 
> > Do you want 30 issues? I don't know which one to pick :D
> 
> Haha nope, this has to be selected by someone that knows about the patches.

https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0010-Add-TCP-fast-open.patch
https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0021-Avoid-creating-buf-copy.patch
https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0024-Reduce-load-on-bungee-by-so-called-BungeeSmasher-s.patch
https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0025-Improve-scheduler.patch
https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0030-EventBus-speed-improvements.patch

**Comment by linsaftw** [comment]
[dfbb7c9](https://github.com/2lstudios-mc/FlameCord/commit/dfbb7c9ccd0222d63069f9861bd34c764540e987)

TCP Fast Open

**Comment by andreasdc** [comment]
> [dfbb7c9](https://github.com/2lstudios-mc/FlameCord/commit/dfbb7c9ccd0222d63069f9861bd34c764540e987) - TCP Fast Open

In Velocity they have fastopen in 2 spots
https://github.com/PaperMC/Velocity/search?q=fastopen

**Comment by linsaftw** [comment]
[e422dfc](https://github.com/2lstudios-mc/FlameCord/commit/e422dfc79eb717c14d0958f2ecf8ba3a98e5c7a1) - InitialHandler Processing State (Not related to IvanCord, but it is a security patch that might be interesting to you guys)
