### ISSUE TITLE
'Disconnected' after applying this patch

### ISSUE THREAD

**Issue by andreasdc** [2lstudios-mc/FlameCord#92]
https://github.com/2lstudios-mc/FlameCord/blob/92cb5776a202df7232e51892a9393a4148ad72d3/Waterfall-Proxy-Patches/0029-InitialHandler-Processing-State.patch#L1
When you apply this patch and cancel PreLoginEvent, you see 'Disconnected' message instead of the actual kick message.

Removing this line fixes the problem:
https://github.com/2lstudios-mc/FlameCord/blob/92cb5776a202df7232e51892a9393a4148ad72d3/Waterfall-Proxy-Patches/0029-InitialHandler-Processing-State.patch#L48

**Comment by linsaftw** [comment]
Thank you very much. This basically means we need to add "State.PROCESSING_USERNAME" to the "can receive kick message" list on InitialHandler class.

**Comment by linsaftw** [comment]
Fixed on e9464dab42d1a51cf557d012309368baafbd128b
