### ISSUE TITLE
FlameCord General Restructuration

### ISSUE THREAD

**Issue by sammwyy** [2lstudios-mc/FlameCord#93]
Properly reload configuration instead of renewing objects.

**Comment by linsaftw** [comment]
renew -> reload
check if instance is null. if so, reload instead of creating a new object.

**Comment by linsaftw** [comment]
Done on [03e6b26](https://github.com/2lstudios-mc/FlameCord/commit/03e6b26318bea58d7f2b1ce6acafe10dbf95cff7)
