### ISSUE TITLE
servers offline message shows ip and port

### ISSUE THREAD

**Issue by TheWylot** [2lstudios-mc/FlameCord#94]
check that thing:
![image](https://user-images.githubusercontent.com/68345215/156752092-341ccd90-f12f-4243-b711-976b4b453f81.png)

**Comment by linsaftw** [comment]
Just change the message in the messages.yml. Remove the exception.

**Comment by linsaftw** [comment]
> > Just change the message in the messages.yml. Remove the exception.
> 
> I'f i'm not wrong, It will remove actual kick message, like whitelist. How to avoid that?

Cannot fix then. The error is took from the spigot instance, not bungee. (The one with the ip)

**Comment by andreasdc** [comment]
> > > Just change the message in the messages.yml. Remove the exception.
> > 
> > 
> > I'f i'm not wrong, It will remove actual kick message, like whitelist. How to avoid that?
> 
> Cannot fix then. The error is took from the spigot instance, not bungee. (The one with the ip)

But spigot is offline so how does it take it from there?

**Comment by linsaftw** [comment]
> > > > Just change the message in the messages.yml. Remove the exception.
> > > 
> > > 
> > > I'f i'm not wrong, It will remove actual kick message, like whitelist. How to avoid that?
> > 
> > 
> > Cannot fix then. The error is took from the spigot instance, not bungee. (The one with the ip)
> 
> But spigot is offline so how does it take it from there?

Sorry, i meant from java.

**Comment by andreasdc** [comment]
> > > > > Just change the message in the messages.yml. Remove the exception.
> > > > 
> > > > 
> > > > I'f i'm not wrong, It will remove actual kick message, like whitelist. How to avoid that?
> > > 
> > > 
> > > Cannot fix then. The error is took from the spigot instance, not bungee. (The one with the ip)
> > 
> > 
> > But spigot is offline so how does it take it from there?
> 
> Sorry, i meant from java.

Is it possible to hide it?

**Comment by linsaftw** [comment]
> > > > > > Just change the message in the messages.yml. Remove the exception.
> > > > > 
> > > > > 
> > > > > I'f i'm not wrong, It will remove actual kick message, like whitelist. How to avoid that?
> > > > 
> > > > 
> > > > Cannot fix then. The error is took from the spigot instance, not bungee. (The one with the ip)
> > > 
> > > 
> > > But spigot is offline so how does it take it from there?
> > 
> > 
> > Sorry, i meant from java.
> 
> Is it possible to hide it?

Not sure, maybe i will investigate.
