### ISSUE TITLE
1.18.1?

### ISSUE THREAD

**Issue by comonier** [2lstudios-mc/FlameCord#95]
hello and open this ticket because the minecraft.mp site recognizes my server as 1.18.1 and I already discarded the fact that it is the lobby or survival that are paper 1.18.2 and without the bungeecord they are recognized as 1.18.2 o what do I do for the proxy to also be ? It insists on classifying my server as 1.18.1 I think it's because of the proxy, I've tried flamecord and bungeecord from the last version that support 1.18.2 but minecraft-mp continues to recognize it as 1.18.1

https://minecraft-mp.com/server-s301137

**Comment by linsaftw** [comment]
Not sure about this. I don't think this has to do with FlameCord at all as it supports 1.18.2 perfectly fine.
