### ISSUE TITLE
credit for patches you didn't create

### ISSUE THREAD

**Issue by MrIvanPlays** [2lstudios-mc/FlameCord#99]
https://github.com/2lstudios-mc/FlameCord/blob/master/Waterfall-Proxy-Patches/0031-Avoid-Copying-Bytebufs.patch
this patch was took from IvanCord: https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0021-Avoid-creating-buf-copy.patch
dates are speaking. making small changes don't wash your hands.

EDIT: https://github.com/2lstudios-mc/FlameCord/blob/master/Waterfall-Proxy-Patches/0027-TCP-Fast-Open.patch
same here https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0010-Add-TCP-fast-open.patch

**Comment by linsaftw** [comment]
This is not applicable as I just took the idea and made it completely from scratch. But yeah, maybe I can write something like "inspired by...".

Anyways, the bytebuf patch is giving me issues so I think I am searching for new ways of doing it or just delete it.

**Comment by linsaftw** [comment]
Closed as 0031 was replaced and 0027 was implemented completely different in the first place.
